use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 11] = [
NpcEntry {
        sprite_id: 0x02,
        x: 20,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 30,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 31,
        y: 20,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 15,
        y: 18,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 1,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 9,
        y: 21,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x31,
        x: 28,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 29,
        y: 26,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x05,
        x: 28,
        y: 26,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 9,
        y: 27,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 4,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x31,
        x: 27,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 6] = [
SignEntry {
        x: 23,
        y: 19,
        text_id: 1,
    },
    SignEntry {
        x: 17,
        y: 29,
        text_id: 2,
    },
    SignEntry {
        x: 26,
        y: 25,
        text_id: 3,
    },
    SignEntry {
        x: 20,
        y: 17,
        text_id: 4,
    },
    SignEntry {
        x: 11,
        y: 25,
        text_id: 5,
    },
    SignEntry {
        x: 27,
        y: 21,
        text_id: 6,
    },
];

pub const WARPS: [WarpData; 10] = [
WarpData {
        x: 27,
        y: 11,
        dest_map: Some(MapId::CeruleanTrashedHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 13,
        y: 15,
        dest_map: Some(MapId::CeruleanTradeHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 19,
        y: 17,
        dest_map: Some(MapId::CeruleanPokecenter),
        dest_warp_id: 0,
    },
    WarpData {
        x: 30,
        y: 19,
        dest_map: Some(MapId::CeruleanGym),
        dest_warp_id: 0,
    },
    WarpData {
        x: 13,
        y: 25,
        dest_map: Some(MapId::BikeShop),
        dest_warp_id: 0,
    },
    WarpData {
        x: 25,
        y: 25,
        dest_map: Some(MapId::CeruleanMart),
        dest_warp_id: 0,
    },
    WarpData {
        x: 4,
        y: 11,
        dest_map: Some(MapId::CeruleanCave1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 27,
        y: 9,
        dest_map: Some(MapId::CeruleanTrashedHouse),
        dest_warp_id: 2,
    },
    WarpData {
        x: 9,
        y: 11,
        dest_map: Some(MapId::CeruleanBadgeHouse),
        dest_warp_id: 1,
    },
    WarpData {
        x: 9,
        y: 9,
        dest_map: Some(MapId::CeruleanBadgeHouse),
        dest_warp_id: 0,
    },
];