use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 13] = [
NpcEntry {
        sprite_id: 0x0E,
        x: 5,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 12,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 30,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 24,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 16,
        y: 23,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 7,
        y: 22,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 30,
        y: 27,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 2,
        y: 20,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x14,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 2,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x0A,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 35,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 36,
        y: 23,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x1D,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 20,
        y: 33,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 12,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x14,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 5,
        y: 32,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 13,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD4,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 15,
    y: 23,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 5] = [
WarpData {
        x: 14,
        y: 35,
        dest_map: None,
        dest_warp_id: 1,
    },
    WarpData {
        x: 15,
        y: 35,
        dest_map: None,
        dest_warp_id: 1,
    },
    WarpData {
        x: 5,
        y: 5,
        dest_map: Some(MapId::MtMoonB1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 17,
        y: 11,
        dest_map: Some(MapId::MtMoonB1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 25,
        y: 15,
        dest_map: Some(MapId::MtMoonB1F),
        dest_warp_id: 3,
    },
];