use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 14] = [
NpcEntry {
        sprite_id: 0x3D,
        x: 9,
        y: 20,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 32,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 21,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 25,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 23,
        y: 34,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 26,
        y: 28,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 21,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 37,
        y: 32,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09,
        x: 4,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 7,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x26,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 28,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x23,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 34,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 12,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 26,
        y: 32,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 13,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xE1,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 20,
        y: 32,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 14,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xE9,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 3] = [
WarpData {
        x: 4,
        y: 35,
        dest_map: None,
        dest_warp_id: 3,
    },
    WarpData {
        x: 5,
        y: 35,
        dest_map: None,
        dest_warp_id: 3,
    },
    WarpData {
        x: 0,
        y: 11,
        dest_map: None,
        dest_warp_id: 3,
    },
];