use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 9] = [
NpcEntry {
        sprite_id: 0x17,
        x: 25,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 29,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 23,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 16,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 26,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 17,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 11,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 18,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 10,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x23,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 9,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xCA,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 12,
        y: 20,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x25,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 25,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x48,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 10,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x4A,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 3] = [
WarpData {
        x: 19,
        y: 10,
        dest_map: Some(MapId::RocketHideoutB3F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 24,
        y: 15,
        dest_map: Some(MapId::RocketHideoutElevator),
        dest_warp_id: 0,
    },
    WarpData {
        x: 25,
        y: 15,
        dest_map: Some(MapId::RocketHideoutElevator),
        dest_warp_id: 1,
    },
];