use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 8] = [
NpcEntry {
        sprite_id: 0x06,
        x: 11,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 6,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 3,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 20,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 30,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 14,
        y: 28,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 33,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 26,
        y: 30,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 5,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 4] = [
WarpData {
        x: 33,
        y: 25,
        dest_map: Some(MapId::RockTunnel1F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 27,
        y: 3,
        dest_map: Some(MapId::RockTunnel1F),
        dest_warp_id: 5,
    },
    WarpData {
        x: 23,
        y: 11,
        dest_map: Some(MapId::RockTunnel1F),
        dest_warp_id: 6,
    },
    WarpData {
        x: 3,
        y: 3,
        dest_map: Some(MapId::RockTunnel1F),
        dest_warp_id: 7,
    },
];