use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 9] = [
NpcEntry {
        sprite_id: 0x0C,
        x: 8,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 13,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 42,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 26,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 26,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 26,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 26,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 46,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 51,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 16,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 17,
    y: 3,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 5] = [
WarpData {
        x: 1,
        y: 9,
        dest_map: Some(MapId::Route8Gate),
        dest_warp_id: 0,
    },
    WarpData {
        x: 1,
        y: 10,
        dest_map: Some(MapId::Route8Gate),
        dest_warp_id: 1,
    },
    WarpData {
        x: 8,
        y: 9,
        dest_map: Some(MapId::Route8Gate),
        dest_warp_id: 2,
    },
    WarpData {
        x: 8,
        y: 10,
        dest_map: Some(MapId::Route8Gate),
        dest_warp_id: 3,
    },
    WarpData {
        x: 13,
        y: 3,
        dest_map: Some(MapId::UndergroundPathRoute8),
        dest_warp_id: 0,
    },
];