use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x07,
        x: 8,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 13,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 13,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 4,
        y: 27,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 16,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 9,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 8,
        y: 43,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 11,
        y: 43,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 9,
        y: 42,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 10,
        y: 44,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 14,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 11,
    y: 9,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 0] = [];