use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x22,
        x: 87,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 68,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 45,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 55,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 24,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 38,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 87,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 34,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 25,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 24,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 16,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 15,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 8,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 2] = [
SignEntry {
        x: 51,
        y: 7,
        text_id: 1,
    },
    SignEntry {
        x: 57,
        y: 11,
        text_id: 2,
    },
];

pub const WARPS: [WarpData; 2] = [
WarpData {
        x: 48,
        y: 5,
        dest_map: Some(MapId::SeafoamIslands1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 58,
        y: 9,
        dest_map: Some(MapId::SeafoamIslands1F),
        dest_warp_id: 2,
    },
];