use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x06,
        x: 13,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 24,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 31,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 48,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 16,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 43,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 22,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 45,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 40,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 10,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xE6,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 25,
    y: 7,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 0] = [];