use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x43,
        x: 10,
        y: 62,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 14,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 5,
        y: 39,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 11,
        y: 92,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 14,
        y: 76,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 20,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 12,
        y: 40,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 9,
        y: 52,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 6,
        y: 87,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 14,
        y: 35,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD8,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 5,
        y: 89,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x25,
    },
];

pub const SIGNS: [SignEntry; 2] = [
SignEntry {
        x: 13,
        y: 13,
        text_id: 1,
    },
    SignEntry {
        x: 11,
        y: 63,
        text_id: 2,
    },
];

pub const WARPS: [WarpData; 4] = [
WarpData {
        x: 10,
        y: 15,
        dest_map: Some(MapId::Route12Gate1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 11,
        y: 15,
        dest_map: Some(MapId::Route12Gate1F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 10,
        y: 21,
        dest_map: Some(MapId::Route12Gate1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 11,
        y: 77,
        dest_map: Some(MapId::Route12SuperRodHouse),
        dest_warp_id: 0,
    },
];