use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 11] = [
NpcEntry {
        sprite_id: 0x06,
        x: 41,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 20,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 53,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 21,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 31,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 35,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 53,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 41,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 48,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 46,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 37,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 22,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 18,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 23,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 18,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xDC,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 39,
    y: 9,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 4] = [
WarpData {
        x: 7,
        y: 8,
        dest_map: Some(MapId::Route15Gate1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 7,
        y: 9,
        dest_map: Some(MapId::Route15Gate1F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 14,
        y: 8,
        dest_map: Some(MapId::Route15Gate1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 14,
        y: 9,
        dest_map: Some(MapId::Route15Gate1F),
        dest_warp_id: 3,
    },
];