use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 11] = [
NpcEntry {
        sprite_id: 0x2C,
        x: 13,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 8,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 28,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20,
        x: 8,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 28,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21,
        x: 18,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 21,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 28,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 29,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 2,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD1,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 4,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x24,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 21,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x30,
    },
    NpcEntry {
        sprite_id: 0x42,
        x: 22,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x42,
        x: 25,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x42,
        x: 24,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 7] = [
WarpData {
        x: 24,
        y: 0,
        dest_map: Some(MapId::SilphCo6F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 26,
        y: 0,
        dest_map: Some(MapId::SilphCo4F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 20,
        y: 0,
        dest_map: Some(MapId::SilphCoElevator),
        dest_warp_id: 0,
    },
    WarpData {
        x: 27,
        y: 3,
        dest_map: Some(MapId::SilphCo7F),
        dest_warp_id: 5,
    },
    WarpData {
        x: 9,
        y: 15,
        dest_map: Some(MapId::SilphCo9F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 11,
        y: 5,
        dest_map: Some(MapId::SilphCo3F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 3,
        y: 15,
        dest_map: Some(MapId::SilphCo3F),
        dest_warp_id: 5,
    },
];