use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 7] = [
NpcEntry {
        sprite_id: 0x04,
        x: 13,
        y: 20,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 30,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 30,
        y: 25,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D,
        x: 17,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x48,
        x: 18,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 6,
        y: 23,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 17,
        y: 5,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 6] = [
SignEntry {
        x: 17,
        y: 17,
        text_id: 1,
    },
    SignEntry {
        x: 19,
        y: 1,
        text_id: 2,
    },
    SignEntry {
        x: 21,
        y: 29,
        text_id: 3,
    },
    SignEntry {
        x: 30,
        y: 19,
        text_id: 4,
    },
    SignEntry {
        x: 24,
        y: 25,
        text_id: 5,
    },
    SignEntry {
        x: 27,
        y: 7,
        text_id: 6,
    },
];

pub const WARPS: [WarpData; 5] = [
WarpData {
        x: 23,
        y: 25,
        dest_map: Some(MapId::ViridianPokecenter),
        dest_warp_id: 0,
    },
    WarpData {
        x: 29,
        y: 19,
        dest_map: Some(MapId::ViridianMart),
        dest_warp_id: 0,
    },
    WarpData {
        x: 21,
        y: 15,
        dest_map: Some(MapId::ViridianSchoolHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 21,
        y: 9,
        dest_map: Some(MapId::ViridianNicknameHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 32,
        y: 7,
        dest_map: Some(MapId::ViridianGym),
        dest_warp_id: 0,
    },
];