use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 9] = [
NpcEntry {
        sprite_id: 0x08,
        x: 8,
        y: 17,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x25,
        x: 11,
        y: 28,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D,
        x: 14,
        y: 19,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 1,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x25,
        x: 25,
        y: 22,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x25,
        x: 22,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 32,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x05,
        x: 30,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 32,
        y: 29,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 42,
        y: 14,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 9] = [
SignEntry {
        x: 27,
        y: 15,
        text_id: 1,
    },
    SignEntry {
        x: 19,
        y: 15,
        text_id: 2,
    },
    SignEntry {
        x: 42,
        y: 9,
        text_id: 3,
    },
    SignEntry {
        x: 13,
        y: 29,
        text_id: 4,
    },
    SignEntry {
        x: 21,
        y: 9,
        text_id: 5,
    },
    SignEntry {
        x: 12,
        y: 13,
        text_id: 6,
    },
    SignEntry {
        x: 39,
        y: 21,
        text_id: 7,
    },
    SignEntry {
        x: 33,
        y: 21,
        text_id: 8,
    },
    SignEntry {
        x: 27,
        y: 21,
        text_id: 9,
    },
];

pub const WARPS: [WarpData; 13] = [
WarpData {
        x: 8,
        y: 13,
        dest_map: Some(MapId::CeladonMart1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 10,
        y: 13,
        dest_map: Some(MapId::CeladonMart1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 24,
        y: 9,
        dest_map: Some(MapId::CeladonMansion1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 24,
        y: 3,
        dest_map: Some(MapId::CeladonMansion1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 25,
        y: 3,
        dest_map: Some(MapId::CeladonMansion1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 41,
        y: 9,
        dest_map: Some(MapId::CeladonPokecenter),
        dest_warp_id: 0,
    },
    WarpData {
        x: 12,
        y: 27,
        dest_map: Some(MapId::CeladonGym),
        dest_warp_id: 0,
    },
    WarpData {
        x: 28,
        y: 19,
        dest_map: Some(MapId::GameCorner),
        dest_warp_id: 0,
    },
    WarpData {
        x: 39,
        y: 19,
        dest_map: Some(MapId::CeladonMart5F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 33,
        y: 19,
        dest_map: Some(MapId::GameCornerPrizeRoom),
        dest_warp_id: 0,
    },
    WarpData {
        x: 31,
        y: 27,
        dest_map: Some(MapId::CeladonDiner),
        dest_warp_id: 0,
    },
    WarpData {
        x: 35,
        y: 27,
        dest_map: Some(MapId::CeladonChiefHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 43,
        y: 27,
        dest_map: Some(MapId::CeladonHotel),
        dest_warp_id: 0,
    },
];