use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x04,
        x: 10,
        y: 12,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 28,
        y: 17,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 30,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 24,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x38,
        x: 31,
        y: 5,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 25,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x05,
        x: 12,
        y: 6,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x05,
        x: 30,
        y: 12,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3C,
        x: 8,
        y: 17,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3E,
        x: 6,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 14] = [
SignEntry {
        x: 15,
        y: 23,
        text_id: 1,
    },
    SignEntry {
        x: 25,
        y: 15,
        text_id: 2,
    },
    SignEntry {
        x: 17,
        y: 5,
        text_id: 3,
    },
    SignEntry {
        x: 6,
        y: 13,
        text_id: 4,
    },
    SignEntry {
        x: 20,
        y: 27,
        text_id: 5,
    },
    SignEntry {
        x: 27,
        y: 29,
        text_id: 6,
    },
    SignEntry {
        x: 21,
        y: 15,
        text_id: 7,
    },
    SignEntry {
        x: 5,
        y: 29,
        text_id: 8,
    },
    SignEntry {
        x: 33,
        y: 7,
        text_id: 9,
    },
    SignEntry {
        x: 27,
        y: 7,
        text_id: 10,
    },
    SignEntry {
        x: 13,
        y: 7,
        text_id: 11,
    },
    SignEntry {
        x: 31,
        y: 13,
        text_id: 12,
    },
    SignEntry {
        x: 13,
        y: 15,
        text_id: 13,
    },
    SignEntry {
        x: 7,
        y: 7,
        text_id: 14,
    },
];

pub const WARPS: [WarpData; 9] = [
WarpData {
        x: 5,
        y: 13,
        dest_map: Some(MapId::FuchsiaMart),
        dest_warp_id: 0,
    },
    WarpData {
        x: 11,
        y: 27,
        dest_map: Some(MapId::FuchsiaBillsGrandpasHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 19,
        y: 27,
        dest_map: Some(MapId::FuchsiaPokecenter),
        dest_warp_id: 0,
    },
    WarpData {
        x: 27,
        y: 27,
        dest_map: Some(MapId::WardensHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 18,
        y: 3,
        dest_map: Some(MapId::SafariZoneGate),
        dest_warp_id: 0,
    },
    WarpData {
        x: 5,
        y: 27,
        dest_map: Some(MapId::FuchsiaGym),
        dest_warp_id: 0,
    },
    WarpData {
        x: 22,
        y: 13,
        dest_map: Some(MapId::FuchsiaMeetingRoom),
        dest_warp_id: 0,
    },
    WarpData {
        x: 31,
        y: 27,
        dest_map: Some(MapId::FuchsiaGoodRodHouse),
        dest_warp_id: 1,
    },
    WarpData {
        x: 31,
        y: 24,
        dest_map: Some(MapId::FuchsiaGoodRodHouse),
        dest_warp_id: 0,
    },
];