use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 11] = [
NpcEntry {
        sprite_id: 0x0F,
        x: 2,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x26,
        x: 5,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0A,
        x: 2,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 2,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x27,
        x: 5,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1C,
        x: 8,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x24,
        x: 8,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 11,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x26,
        x: 14,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 17,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 9,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 11,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 7,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 9,
    y: 4,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 3] = [
WarpData {
        x: 15,
        y: 17,
        dest_map: None,
        dest_warp_id: 7,
    },
    WarpData {
        x: 16,
        y: 17,
        dest_map: None,
        dest_warp_id: 7,
    },
    WarpData {
        x: 17,
        y: 4,
        dest_map: Some(MapId::RocketHideoutB1F),
        dest_warp_id: 1,
    },
];