use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 7] = [
NpcEntry {
        sprite_id: 0x0E,
        x: 7,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 5,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 17,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 23,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 37,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 17,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 22,
        y: 24,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 18,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 32,
        y: 24,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 19,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 11,
    y: 29,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 8] = [
WarpData {
        x: 15,
        y: 3,
        dest_map: None,
        dest_warp_id: 1,
    },
    WarpData {
        x: 15,
        y: 0,
        dest_map: None,
        dest_warp_id: 1,
    },
    WarpData {
        x: 15,
        y: 33,
        dest_map: None,
        dest_warp_id: 2,
    },
    WarpData {
        x: 15,
        y: 35,
        dest_map: None,
        dest_warp_id: 2,
    },
    WarpData {
        x: 37,
        y: 3,
        dest_map: Some(MapId::RockTunnelB1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 5,
        y: 3,
        dest_map: Some(MapId::RockTunnelB1F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 17,
        y: 11,
        dest_map: Some(MapId::RockTunnelB1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 37,
        y: 17,
        dest_map: Some(MapId::RockTunnelB1F),
        dest_warp_id: 3,
    },
];