use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 7] = [
NpcEntry {
        sprite_id: 0x18,
        x: 26,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 12,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 18,
        y: 17,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 15,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 28,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 11,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x1D,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 9,
        y: 17,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x12,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 5] = [
WarpData {
        x: 23,
        y: 2,
        dest_map: Some(MapId::RocketHideoutB2F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 21,
        y: 2,
        dest_map: Some(MapId::GameCorner),
        dest_warp_id: 2,
    },
    WarpData {
        x: 24,
        y: 19,
        dest_map: Some(MapId::RocketHideoutElevator),
        dest_warp_id: 0,
    },
    WarpData {
        x: 21,
        y: 24,
        dest_map: Some(MapId::RocketHideoutB2F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 25,
        y: 19,
        dest_map: Some(MapId::RocketHideoutElevator),
        dest_warp_id: 1,
    },
];