use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x0B,
        x: 10,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 26,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 13,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 36,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 12,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 22,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 45,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 33,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 43,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 45,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 12,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 22,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 12,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 1] = [
SignEntry {
    x: 1,
    y: 5,
    text_id: 1,
}
];

pub const WARPS: [WarpData; 5] = [
WarpData {
        x: 49,
        y: 8,
        dest_map: Some(MapId::Route11Gate1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 49,
        y: 9,
        dest_map: Some(MapId::Route11Gate1F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 58,
        y: 8,
        dest_map: Some(MapId::Route11Gate1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 58,
        y: 9,
        dest_map: Some(MapId::Route11Gate1F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 4,
        y: 5,
        dest_map: Some(MapId::DiglettsCaveRoute11),
        dest_warp_id: 0,
    },
];