use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x07,
        x: 49,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 48,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 27,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 23,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 50,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 12,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 33,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 32,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 10,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 7,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 3,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 3] = [
SignEntry {
        x: 15,
        y: 13,
        text_id: 1,
    },
    SignEntry {
        x: 33,
        y: 5,
        text_id: 2,
    },
    SignEntry {
        x: 31,
        y: 11,
        text_id: 3,
    },
];

pub const WARPS: [WarpData; 0] = [];