use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x12,
        x: 12,
        y: 19,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 11,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 4,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 7,
        y: 32,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 14,
        y: 34,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 17,
        y: 58,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 2,
        y: 68,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 14,
        y: 98,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 5,
        y: 98,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 10,
        y: 118,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 12,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 6] = [
SignEntry {
        x: 9,
        y: 51,
        text_id: 1,
    },
    SignEntry {
        x: 9,
        y: 63,
        text_id: 2,
    },
    SignEntry {
        x: 9,
        y: 75,
        text_id: 3,
    },
    SignEntry {
        x: 9,
        y: 87,
        text_id: 4,
    },
    SignEntry {
        x: 9,
        y: 111,
        text_id: 5,
    },
    SignEntry {
        x: 9,
        y: 141,
        text_id: 6,
    },
];

pub const WARPS: [WarpData; 0] = [];