use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 7] = [
NpcEntry {
        sprite_id: 0x12,
        x: 17,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 14,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 11,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 9,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 6,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 3,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x43,
        x: 26,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 2] = [
SignEntry {
        x: 27,
        y: 11,
        text_id: 1,
    },
    SignEntry {
        x: 5,
        y: 17,
        text_id: 2,
    },
];

pub const WARPS: [WarpData; 9] = [
WarpData {
        x: 17,
        y: 10,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 17,
        y: 11,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 24,
        y: 10,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 24,
        y: 11,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 17,
        y: 4,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 17,
        y: 5,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 5,
    },
    WarpData {
        x: 24,
        y: 4,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 6,
    },
    WarpData {
        x: 24,
        y: 5,
        dest_map: Some(MapId::Route16Gate1F),
        dest_warp_id: 7,
    },
    WarpData {
        x: 7,
        y: 5,
        dest_map: Some(MapId::Route16FlyHouse),
        dest_warp_id: 0,
    },
];