use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 15] = [
NpcEntry {
        sprite_id: 0x18,
        x: 7,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 20,
        y: 8,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 34,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 13,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 11,
        y: 25,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 32,
        y: 13,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 18,
        y: 30,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20,
        x: 8,
        y: 14,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C,
        x: 23,
        y: 23,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B,
        x: 17,
        y: 30,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 30,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09,
        x: 31,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 12,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21,
        x: 18,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 13,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 18,
        y: 22,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 14,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 19,
        y: 22,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 15,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 10] = [
SignEntry {
        x: 17,
        y: 5,
        text_id: 1,
    },
    SignEntry {
        x: 27,
        y: 5,
        text_id: 2,
    },
    SignEntry {
        x: 35,
        y: 5,
        text_id: 3,
    },
    SignEntry {
        x: 26,
        y: 11,
        text_id: 4,
    },
    SignEntry {
        x: 39,
        y: 19,
        text_id: 5,
    },
    SignEntry {
        x: 5,
        y: 21,
        text_id: 6,
    },
    SignEntry {
        x: 15,
        y: 21,
        text_id: 7,
    },
    SignEntry {
        x: 10,
        y: 29,
        text_id: 8,
    },
    SignEntry {
        x: 27,
        y: 29,
        text_id: 9,
    },
    SignEntry {
        x: 1,
        y: 19,
        text_id: 10,
    },
];

pub const WARPS: [WarpData; 8] = [
WarpData {
        x: 7,
        y: 5,
        dest_map: Some(MapId::CopycatsHouse1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 26,
        y: 3,
        dest_map: Some(MapId::FightingDojo),
        dest_warp_id: 0,
    },
    WarpData {
        x: 34,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 0,
    },
    WarpData {
        x: 13,
        y: 11,
        dest_map: Some(MapId::SaffronPidgeyHouse),
        dest_warp_id: 0,
    },
    WarpData {
        x: 25,
        y: 11,
        dest_map: Some(MapId::SaffronMart),
        dest_warp_id: 0,
    },
    WarpData {
        x: 18,
        y: 21,
        dest_map: Some(MapId::SilphCo1F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 9,
        y: 29,
        dest_map: Some(MapId::SaffronPokecenter),
        dest_warp_id: 0,
    },
    WarpData {
        x: 29,
        y: 29,
        dest_map: Some(MapId::MrPsychicsHouse),
        dest_warp_id: 0,
    },
];