use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 9] = [
NpcEntry {
        sprite_id: 0x0D,
        x: 9,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 40,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x19,
        x: 10,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 45,
        trainer_set: 22,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 17,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 19,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x19,
        x: 3,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 45,
        trainer_set: 23,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 17,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 19,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x19,
        x: 3,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 45,
        trainer_set: 24,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 17,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 19,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 3,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 19,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x24,
        x: 10,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 32] = [
WarpData {
        x: 8,
        y: 17,
        dest_map: None,
        dest_warp_id: 2,
    },
    WarpData {
        x: 9,
        y: 17,
        dest_map: None,
        dest_warp_id: 2,
    },
    WarpData {
        x: 1,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 22,
    },
    WarpData {
        x: 5,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 15,
    },
    WarpData {
        x: 1,
        y: 5,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 18,
    },
    WarpData {
        x: 5,
        y: 5,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 8,
    },
    WarpData {
        x: 1,
        y: 9,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 27,
    },
    WarpData {
        x: 5,
        y: 9,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 16,
    },
    WarpData {
        x: 1,
        y: 11,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 5,
    },
    WarpData {
        x: 5,
        y: 11,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 13,
    },
    WarpData {
        x: 1,
        y: 15,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 23,
    },
    WarpData {
        x: 5,
        y: 15,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 30,
    },
    WarpData {
        x: 1,
        y: 17,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 17,
    },
    WarpData {
        x: 5,
        y: 17,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 9,
    },
    WarpData {
        x: 9,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 26,
    },
    WarpData {
        x: 11,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 3,
    },
    WarpData {
        x: 9,
        y: 5,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 7,
    },
    WarpData {
        x: 11,
        y: 5,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 12,
    },
    WarpData {
        x: 11,
        y: 11,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 4,
    },
    WarpData {
        x: 11,
        y: 15,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 31,
    },
    WarpData {
        x: 15,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 24,
    },
    WarpData {
        x: 19,
        y: 3,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 28,
    },
    WarpData {
        x: 15,
        y: 5,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 2,
    },
    WarpData {
        x: 19,
        y: 5,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 10,
    },
    WarpData {
        x: 15,
        y: 9,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 20,
    },
    WarpData {
        x: 19,
        y: 9,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 29,
    },
    WarpData {
        x: 15,
        y: 11,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 14,
    },
    WarpData {
        x: 19,
        y: 11,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 6,
    },
    WarpData {
        x: 15,
        y: 15,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 21,
    },
    WarpData {
        x: 19,
        y: 15,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 25,
    },
    WarpData {
        x: 15,
        y: 17,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 11,
    },
    WarpData {
        x: 19,
        y: 17,
        dest_map: Some(MapId::SaffronGym),
        dest_warp_id: 19,
    },
];