use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 11] = [
NpcEntry {
        sprite_id: 0x2C,
        x: 1,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C,
        x: 13,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C,
        x: 7,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B,
        x: 10,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 13,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 32,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20,
        x: 2,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 28,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 20,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 33,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 19,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 34,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x02,
        x: 3,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 1,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x27,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 24,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xCB,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 6] = [
WarpData {
        x: 16,
        y: 0,
        dest_map: Some(MapId::SilphCo8F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 22,
        y: 0,
        dest_map: Some(MapId::SilphCo6F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 18,
        y: 0,
        dest_map: Some(MapId::SilphCoElevator),
        dest_warp_id: 0,
    },
    WarpData {
        x: 5,
        y: 7,
        dest_map: Some(MapId::SilphCo11F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 5,
        y: 3,
        dest_map: Some(MapId::SilphCo3F),
        dest_warp_id: 8,
    },
    WarpData {
        x: 21,
        y: 15,
        dest_map: Some(MapId::SilphCo5F),
        dest_warp_id: 3,
    },
];