use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 13] = [
NpcEntry {
        sprite_id: 0x10,
        x: 10,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 41,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 13,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 0,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 41,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 2,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 1,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 12,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x51,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 21,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x25,
        x: 22,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 0,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 12,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x35,
        x: 11,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1D,
        x: 22,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 12,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 20,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 13,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 12] = [
WarpData {
        x: 2,
        y: 5,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 3,
        y: 5,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 12,
        y: 5,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 13,
        y: 5,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 22,
        y: 5,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 23,
        y: 5,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 2,
        y: 15,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 3,
        y: 15,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 12,
        y: 15,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 13,
        y: 15,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 22,
        y: 15,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 5,
    },
    WarpData {
        x: 23,
        y: 15,
        dest_map: Some(MapId::SSAnne2F),
        dest_warp_id: 5,
    },
];