use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 11] = [
NpcEntry {
        sprite_id: 0x10,
        x: 2,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 41,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 11,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 41,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 11,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 13,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D,
        x: 22,
        y: 3,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 1,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0A,
        x: 0,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x08,
        x: 2,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x38,
        x: 3,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D,
        x: 10,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 12,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD0,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 21,
        y: 13,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 6] = [
WarpData {
        x: 0,
        y: 0,
        dest_map: Some(MapId::SSAnne1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 10,
        y: 0,
        dest_map: Some(MapId::SSAnne1F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 20,
        y: 0,
        dest_map: Some(MapId::SSAnne1F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 0,
        y: 10,
        dest_map: Some(MapId::SSAnne1F),
        dest_warp_id: 5,
    },
    WarpData {
        x: 10,
        y: 10,
        dest_map: Some(MapId::SSAnne1F),
        dest_warp_id: 6,
    },
    WarpData {
        x: 20,
        y: 10,
        dest_map: Some(MapId::SSAnne1F),
        dest_warp_id: 7,
    },
];