use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 10] = [
NpcEntry {
        sprite_id: 0x07,
        x: 28,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 31,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 7,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 32,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 6,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 31,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 13,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 32,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 26,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x36,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 7,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xF7,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 22,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 13,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 24,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 22,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 4] = [
WarpData {
        x: 23,
        y: 7,
        dest_map: Some(MapId::VictoryRoad2F),
        dest_warp_id: 3,
    },
    WarpData {
        x: 26,
        y: 8,
        dest_map: Some(MapId::VictoryRoad2F),
        dest_warp_id: 5,
    },
    WarpData {
        x: 27,
        y: 15,
        dest_map: Some(MapId::VictoryRoad2F),
        dest_warp_id: 4,
    },
    WarpData {
        x: 2,
        y: 0,
        dest_map: Some(MapId::VictoryRoad2F),
        dest_warp_id: 6,
    },
];