use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 13] = [
NpcEntry {
        sprite_id: 0x0E,
        x: 12,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 24,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 21,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 21,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 19,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 22,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 4,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 26,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 21,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09,
        x: 11,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 27,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD9,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 18,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x34,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 9,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xCD,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 11,
        y: 0,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x37,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 4,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 5,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 12,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F,
        x: 23,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 13,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 0] = [

];

pub const WARPS: [WarpData; 7] = [
WarpData {
        x: 0,
        y: 8,
        dest_map: Some(MapId::VictoryRoad1F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 29,
        y: 7,
        dest_map: None,
        dest_warp_id: 3,
    },
    WarpData {
        x: 29,
        y: 8,
        dest_map: None,
        dest_warp_id: 3,
    },
    WarpData {
        x: 23,
        y: 7,
        dest_map: Some(MapId::VictoryRoad3F),
        dest_warp_id: 0,
    },
    WarpData {
        x: 25,
        y: 14,
        dest_map: Some(MapId::VictoryRoad3F),
        dest_warp_id: 2,
    },
    WarpData {
        x: 27,
        y: 7,
        dest_map: Some(MapId::VictoryRoad3F),
        dest_warp_id: 1,
    },
    WarpData {
        x: 1,
        y: 1,
        dest_map: Some(MapId::VictoryRoad3F),
        dest_warp_id: 3,
    },
];