use crate::maps::MapId;
use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};
use crate::sign_data::SignEntry;
use crate::map_objects::WarpData;

pub const NPCS: [NpcEntry; 8] = [
NpcEntry {
        sprite_id: 0x04,
        x: 16,
        y: 43,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 30,
        y: 33,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 30,
        y: 19,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 2,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 25,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x0B,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 12,
        y: 29,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x14,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 1,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x04,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 27,
        y: 40,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub const SIGNS: [SignEntry; 6] = [
SignEntry {
        x: 24,
        y: 40,
        text_id: 1,
    },
    SignEntry {
        x: 16,
        y: 32,
        text_id: 2,
    },
    SignEntry {
        x: 26,
        y: 17,
        text_id: 3,
    },
    SignEntry {
        x: 4,
        y: 24,
        text_id: 4,
    },
    SignEntry {
        x: 18,
        y: 45,
        text_id: 5,
    },
    SignEntry {
        x: 2,
        y: 1,
        text_id: 6,
    },
];

pub const WARPS: [WarpData; 6] = [
WarpData {
        x: 1,
        y: 0,
        dest_map: Some(MapId::ViridianForestNorthGate),
        dest_warp_id: 2,
    },
    WarpData {
        x: 2,
        y: 0,
        dest_map: Some(MapId::ViridianForestNorthGate),
        dest_warp_id: 3,
    },
    WarpData {
        x: 15,
        y: 47,
        dest_map: Some(MapId::ViridianForestSouthGate),
        dest_warp_id: 1,
    },
    WarpData {
        x: 16,
        y: 47,
        dest_map: Some(MapId::ViridianForestSouthGate),
        dest_warp_id: 1,
    },
    WarpData {
        x: 17,
        y: 47,
        dest_map: Some(MapId::ViridianForestSouthGate),
        dest_warp_id: 1,
    },
    WarpData {
        x: 18,
        y: 47,
        dest_map: Some(MapId::ViridianForestSouthGate),
        dest_warp_id: 1,
    },
];