use std::env;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::Path;

fn main() {
    // Only generate embedded resources for wasm32 target
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let is_wasm32 = target_arch == "wasm32";

    // Get the absolute path to the gfx directory
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let gfx_dir = Path::new(&manifest_dir).join("../../../gfx");
    let gfx_dir = gfx_dir.canonicalize().unwrap_or_else(|_| gfx_dir);

    // Tell cargo to rerun this script if gfx directory changes
    if gfx_dir.exists() {
        println!("cargo:rerun-if-changed={}", gfx_dir.display());
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_assets.rs");
    let mut file = BufWriter::new(File::create(&dest_path).unwrap());

    if is_wasm32 && gfx_dir.exists() {
        generate_embedded_assets(&mut file, &gfx_dir);
    } else {
        // For non-wasm32 or missing gfx directory, generate empty stub
        generate_empty_stub(&mut file);
    }

    file.flush().unwrap();
}

fn generate_embedded_assets<W: Write>(mut writer: W, gfx_dir: &Path) {
    writeln!(writer, "// Auto-generated embedded assets for wasm32").unwrap();
    writeln!(writer, "// Do not edit manually - generated by build.rs").unwrap();
    writeln!(writer).unwrap();
    writeln!(writer, "use std::collections::HashMap;").unwrap();
    writeln!(writer, "use std::sync::OnceLock;").unwrap();
    writeln!(writer).unwrap();

    // Collect all PNG files with their relative paths and absolute paths
    let mut assets: Vec<(String, String)> = Vec::new();

    collect_png_files(gfx_dir, gfx_dir, &mut assets);

    // Sort for consistent output
    assets.sort_by(|a, b| a.0.cmp(&b.0));

    if assets.is_empty() {
        // No assets found, generate empty stub
        writeln!(writer, "// No embedded assets available").unwrap();
        writeln!(
            writer,
            "pub fn get_embedded_asset(_relative_path: &str) -> Option<&'static [u8]> {{"
        )
        .unwrap();
        writeln!(writer, "    None").unwrap();
        writeln!(writer, "}}").unwrap();
        writeln!(writer).unwrap();
        writeln!(
            writer,
            "pub fn list_embedded_assets() -> &'static [&'static str] {{"
        )
        .unwrap();
        writeln!(writer, "    &[]").unwrap();
        writeln!(writer, "}}").unwrap();
        return;
    }

    // Generate static byte arrays for each asset using absolute paths
    for (i, (_, abs_path)) in assets.iter().enumerate() {
        writeln!(
            writer,
            "static ASSET_{}: &[u8] = include_bytes!(r\"{}\");",
            i,
            abs_path.replace("\\", "\\\\")
        )
        .unwrap();
    }

    writeln!(writer).unwrap();

    // Generate the lookup function
    writeln!(writer, "/// Get embedded asset data by relative path").unwrap();
    writeln!(
        writer,
        "pub fn get_embedded_asset(relative_path: &str) -> Option<&'static [u8]> {{"
    )
    .unwrap();
    writeln!(writer, "    // Normalize the path").unwrap();
    writeln!(
        writer,
        "    let normalized = relative_path.replace('\\\\', \"/\").to_lowercase();"
    )
    .unwrap();
    writeln!(writer).unwrap();
    writeln!(
        writer,
        "    static ASSETS: OnceLock<HashMap<&'static str, &'static [u8]>> = OnceLock::new();"
    )
    .unwrap();
    writeln!(writer, "    let map = ASSETS.get_or_init(|| {{").unwrap();
    writeln!(writer, "        let mut m = HashMap::new();").unwrap();

    for (i, (rel_path, _)) in assets.iter().enumerate() {
        // Store both original and lowercase versions
        writeln!(
            writer,
            "        m.insert(\"{}\", ASSET_{} as &'static [u8]);",
            rel_path.to_lowercase(),
            i
        )
        .unwrap();
    }

    writeln!(writer, "        m").unwrap();
    writeln!(writer, "    }});").unwrap();
    writeln!(writer).unwrap();
    writeln!(writer, "    map.get(normalized.as_str()).copied()").unwrap();
    writeln!(writer, "}}").unwrap();

    writeln!(writer).unwrap();
    writeln!(writer, "// List all embedded asset paths").unwrap();
    writeln!(
        writer,
        "pub fn list_embedded_assets() -> &'static [&'static str] {{"
    )
    .unwrap();
    writeln!(writer, "    static PATHS: &[&str] = &[").unwrap();

    for (rel_path, _) in &assets {
        writeln!(writer, "        \"{}\",", rel_path).unwrap();
    }

    writeln!(writer, "    ];").unwrap();
    writeln!(writer, "    PATHS").unwrap();
    writeln!(writer, "}}").unwrap();
}

fn generate_empty_stub<W: Write>(mut writer: W) {
    writeln!(writer, "// Empty stub for non-wasm32 targets").unwrap();
    writeln!(writer).unwrap();
    writeln!(
        writer,
        "// Get embedded asset data by relative path (not available on non-wasm32)"
    )
    .unwrap();
    writeln!(
        writer,
        "pub fn get_embedded_asset(_relative_path: &str) -> Option<&'static [u8]> {{"
    )
    .unwrap();
    writeln!(writer, "    None").unwrap();
    writeln!(writer, "}}").unwrap();
    writeln!(writer).unwrap();
    writeln!(
        writer,
        "// List all embedded asset paths (empty on non-wasm32)"
    )
    .unwrap();
    writeln!(
        writer,
        "pub fn list_embedded_assets() -> &'static [&'static str] {{"
    )
    .unwrap();
    writeln!(writer, "    &[]").unwrap();
    writeln!(writer, "}}").unwrap();
}

fn collect_png_files(base_dir: &Path, current_dir: &Path, assets: &mut Vec<(String, String)>) {
    if let Ok(entries) = fs::read_dir(current_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_png_files(base_dir, &path, assets);
            } else if path.extension().map(|e| e == "png").unwrap_or(false) {
                // Get relative path from gfx directory
                if let Ok(rel_path) = path.strip_prefix(base_dir) {
                    let rel_path_str = rel_path.to_string_lossy().replace("\\", "/");
                    // Get absolute path for include_bytes!
                    let abs_path_str = path.to_string_lossy().replace("\\", "/");
                    assets.push((rel_path_str, abs_path_str));
                }
            }
        }
    }
}
