use crate::maps::MapId;

static AGATHASROOM_BLK: &[u8] = include_bytes!("../../../../maps/AgathasRoom.blk");
static BIKESHOP_BLK: &[u8] = include_bytes!("../../../../maps/BikeShop.blk");
static BILLSHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/BillsHouse.blk");
static BLUESHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/BluesHouse.blk");
static BRUNOSROOM_BLK: &[u8] = include_bytes!("../../../../maps/BrunosRoom.blk");
static CELADONCHIEFHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/CeladonChiefHouse.blk");
static CELADONCITY_BLK: &[u8] = include_bytes!("../../../../maps/CeladonCity.blk");
static CELADONDINER_BLK: &[u8] = include_bytes!("../../../../maps/CeladonDiner.blk");
static CELADONGYM_BLK: &[u8] = include_bytes!("../../../../maps/CeladonGym.blk");
static CELADONHOTEL_BLK: &[u8] = include_bytes!("../../../../maps/CeladonHotel.blk");
static CELADONMANSION1F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMansion1F.blk");
static CELADONMANSION2F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMansion2F.blk");
static CELADONMANSION3F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMansion3F.blk");
static CELADONMANSIONROOF_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMansionRoof.blk");
static CELADONMANSIONROOFHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMansionRoofHouse.blk");
static CELADONMART1F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMart1F.blk");
static CELADONMART2F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMart2F.blk");
static CELADONMART3F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMart3F.blk");
static CELADONMART4F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMart4F.blk");
static CELADONMART5F_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMart5F.blk");
static CELADONMARTELEVATOR_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMartElevator.blk");
static CELADONMARTROOF_BLK: &[u8] = include_bytes!("../../../../maps/CeladonMartRoof.blk");
static CELADONPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/CeladonPokecenter.blk");
static CERULEANBADGEHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanBadgeHouse.blk");
static CERULEANCAVE1F_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanCave1F.blk");
static CERULEANCAVE2F_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanCave2F.blk");
static CERULEANCAVEB1F_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanCaveB1F.blk");
static CERULEANCITY_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanCity.blk");
static CERULEANGYM_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanGym.blk");
static CERULEANMART_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanMart.blk");
static CERULEANPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanPokecenter.blk");
static CERULEANTRADEHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanTradeHouse.blk");
static CERULEANTRASHEDHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/CeruleanTrashedHouse.blk");
static CHAMPIONSROOM_BLK: &[u8] = include_bytes!("../../../../maps/ChampionsRoom.blk");
static CINNABARGYM_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarGym.blk");
static CINNABARISLAND_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarIsland.blk");
static CINNABARLAB_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarLab.blk");
static CINNABARLABFOSSILROOM_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarLabFossilRoom.blk");
static CINNABARLABMETRONOMEROOM_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarLabMetronomeRoom.blk");
static CINNABARLABTRADEROOM_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarLabTradeRoom.blk");
static CINNABARMART_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarMart.blk");
static CINNABARPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/CinnabarPokecenter.blk");
static COLOSSEUM_BLK: &[u8] = include_bytes!("../../../../maps/Colosseum.blk");
static COPYCATSHOUSE1F_BLK: &[u8] = include_bytes!("../../../../maps/CopycatsHouse1F.blk");
static COPYCATSHOUSE2F_BLK: &[u8] = include_bytes!("../../../../maps/CopycatsHouse2F.blk");
static DAYCARE_BLK: &[u8] = include_bytes!("../../../../maps/Daycare.blk");
static DIGLETTSCAVE_BLK: &[u8] = include_bytes!("../../../../maps/DiglettsCave.blk");
static DIGLETTSCAVEROUTE11_BLK: &[u8] = include_bytes!("../../../../maps/DiglettsCaveRoute11.blk");
static DIGLETTSCAVEROUTE2_BLK: &[u8] = include_bytes!("../../../../maps/DiglettsCaveRoute2.blk");
static FIGHTINGDOJO_BLK: &[u8] = include_bytes!("../../../../maps/FightingDojo.blk");
static FUCHSIABILLSGRANDPASHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaBillsGrandpasHouse.blk");
static FUCHSIACITY_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaCity.blk");
static FUCHSIAGOODRODHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaGoodRodHouse.blk");
static FUCHSIAGYM_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaGym.blk");
static FUCHSIAMART_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaMart.blk");
static FUCHSIAMEETINGROOM_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaMeetingRoom.blk");
static FUCHSIAPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/FuchsiaPokecenter.blk");
static GAMECORNER_BLK: &[u8] = include_bytes!("../../../../maps/GameCorner.blk");
static GAMECORNERPRIZEROOM_BLK: &[u8] = include_bytes!("../../../../maps/GameCornerPrizeRoom.blk");
static HALLOFFAME_BLK: &[u8] = include_bytes!("../../../../maps/HallOfFame.blk");
static INDIGOPLATEAU_BLK: &[u8] = include_bytes!("../../../../maps/IndigoPlateau.blk");
static INDIGOPLATEAULOBBY_BLK: &[u8] = include_bytes!("../../../../maps/IndigoPlateauLobby.blk");
static LANCESROOM_BLK: &[u8] = include_bytes!("../../../../maps/LancesRoom.blk");
static LAVENDERCUBONEHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/LavenderCuboneHouse.blk");
static LAVENDERMART_BLK: &[u8] = include_bytes!("../../../../maps/LavenderMart.blk");
static LAVENDERPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/LavenderPokecenter.blk");
static LAVENDERTOWN_BLK: &[u8] = include_bytes!("../../../../maps/LavenderTown.blk");
static LORELEISROOM_BLK: &[u8] = include_bytes!("../../../../maps/LoreleisRoom.blk");
static MRFUJISHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/MrFujisHouse.blk");
static MRPSYCHICSHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/MrPsychicsHouse.blk");
static MTMOON1F_BLK: &[u8] = include_bytes!("../../../../maps/MtMoon1F.blk");
static MTMOONB1F_BLK: &[u8] = include_bytes!("../../../../maps/MtMoonB1F.blk");
static MTMOONB2F_BLK: &[u8] = include_bytes!("../../../../maps/MtMoonB2F.blk");
static MTMOONPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/MtMoonPokecenter.blk");
static MUSEUM1F_BLK: &[u8] = include_bytes!("../../../../maps/Museum1F.blk");
static MUSEUM2F_BLK: &[u8] = include_bytes!("../../../../maps/Museum2F.blk");
static NAMERATERSHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/NameRatersHouse.blk");
static OAKSLAB_BLK: &[u8] = include_bytes!("../../../../maps/OaksLab.blk");
static PALLETTOWN_BLK: &[u8] = include_bytes!("../../../../maps/PalletTown.blk");
static PEWTERCITY_BLK: &[u8] = include_bytes!("../../../../maps/PewterCity.blk");
static PEWTERGYM_BLK: &[u8] = include_bytes!("../../../../maps/PewterGym.blk");
static PEWTERMART_BLK: &[u8] = include_bytes!("../../../../maps/PewterMart.blk");
static PEWTERNIDORANHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/PewterNidoranHouse.blk");
static PEWTERPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/PewterPokecenter.blk");
static PEWTERSPEECHHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/PewterSpeechHouse.blk");
static POKEMONFANCLUB_BLK: &[u8] = include_bytes!("../../../../maps/PokemonFanClub.blk");
static POKEMONMANSION1F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonMansion1F.blk");
static POKEMONMANSION2F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonMansion2F.blk");
static POKEMONMANSION3F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonMansion3F.blk");
static POKEMONMANSIONB1F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonMansionB1F.blk");
static POKEMONTOWER1F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower1F.blk");
static POKEMONTOWER2F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower2F.blk");
static POKEMONTOWER3F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower3F.blk");
static POKEMONTOWER4F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower4F.blk");
static POKEMONTOWER5F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower5F.blk");
static POKEMONTOWER6F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower6F.blk");
static POKEMONTOWER7F_BLK: &[u8] = include_bytes!("../../../../maps/PokemonTower7F.blk");
static POWERPLANT_BLK: &[u8] = include_bytes!("../../../../maps/PowerPlant.blk");
static REDSHOUSE1F_BLK: &[u8] = include_bytes!("../../../../maps/RedsHouse1F.blk");
static REDSHOUSE2F_BLK: &[u8] = include_bytes!("../../../../maps/RedsHouse2F.blk");
static ROCKTUNNEL1F_BLK: &[u8] = include_bytes!("../../../../maps/RockTunnel1F.blk");
static ROCKTUNNELB1F_BLK: &[u8] = include_bytes!("../../../../maps/RockTunnelB1F.blk");
static ROCKTUNNELPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/RockTunnelPokecenter.blk");
static ROCKETHIDEOUTB1F_BLK: &[u8] = include_bytes!("../../../../maps/RocketHideoutB1F.blk");
static ROCKETHIDEOUTB2F_BLK: &[u8] = include_bytes!("../../../../maps/RocketHideoutB2F.blk");
static ROCKETHIDEOUTB3F_BLK: &[u8] = include_bytes!("../../../../maps/RocketHideoutB3F.blk");
static ROCKETHIDEOUTB4F_BLK: &[u8] = include_bytes!("../../../../maps/RocketHideoutB4F.blk");
static ROCKETHIDEOUTELEVATOR_BLK: &[u8] = include_bytes!("../../../../maps/RocketHideoutElevator.blk");
static ROUTE1_BLK: &[u8] = include_bytes!("../../../../maps/Route1.blk");
static ROUTE10_BLK: &[u8] = include_bytes!("../../../../maps/Route10.blk");
static ROUTE11_BLK: &[u8] = include_bytes!("../../../../maps/Route11.blk");
static ROUTE11GATE1F_BLK: &[u8] = include_bytes!("../../../../maps/Route11Gate1F.blk");
static ROUTE11GATE2F_BLK: &[u8] = include_bytes!("../../../../maps/Route11Gate2F.blk");
static ROUTE12_BLK: &[u8] = include_bytes!("../../../../maps/Route12.blk");
static ROUTE12GATE1F_BLK: &[u8] = include_bytes!("../../../../maps/Route12Gate1F.blk");
static ROUTE12GATE2F_BLK: &[u8] = include_bytes!("../../../../maps/Route12Gate2F.blk");
static ROUTE12SUPERRODHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/Route12SuperRodHouse.blk");
static ROUTE13_BLK: &[u8] = include_bytes!("../../../../maps/Route13.blk");
static ROUTE14_BLK: &[u8] = include_bytes!("../../../../maps/Route14.blk");
static ROUTE15_BLK: &[u8] = include_bytes!("../../../../maps/Route15.blk");
static ROUTE15GATE1F_BLK: &[u8] = include_bytes!("../../../../maps/Route15Gate1F.blk");
static ROUTE15GATE2F_BLK: &[u8] = include_bytes!("../../../../maps/Route15Gate2F.blk");
static ROUTE16_BLK: &[u8] = include_bytes!("../../../../maps/Route16.blk");
static ROUTE16FLYHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/Route16FlyHouse.blk");
static ROUTE16GATE1F_BLK: &[u8] = include_bytes!("../../../../maps/Route16Gate1F.blk");
static ROUTE16GATE2F_BLK: &[u8] = include_bytes!("../../../../maps/Route16Gate2F.blk");
static ROUTE17_BLK: &[u8] = include_bytes!("../../../../maps/Route17.blk");
static ROUTE18_BLK: &[u8] = include_bytes!("../../../../maps/Route18.blk");
static ROUTE18GATE1F_BLK: &[u8] = include_bytes!("../../../../maps/Route18Gate1F.blk");
static ROUTE18GATE2F_BLK: &[u8] = include_bytes!("../../../../maps/Route18Gate2F.blk");
static ROUTE19_BLK: &[u8] = include_bytes!("../../../../maps/Route19.blk");
static ROUTE2_BLK: &[u8] = include_bytes!("../../../../maps/Route2.blk");
static ROUTE20_BLK: &[u8] = include_bytes!("../../../../maps/Route20.blk");
static ROUTE21_BLK: &[u8] = include_bytes!("../../../../maps/Route21.blk");
static ROUTE22_BLK: &[u8] = include_bytes!("../../../../maps/Route22.blk");
static ROUTE22GATE_BLK: &[u8] = include_bytes!("../../../../maps/Route22Gate.blk");
static ROUTE23_BLK: &[u8] = include_bytes!("../../../../maps/Route23.blk");
static ROUTE24_BLK: &[u8] = include_bytes!("../../../../maps/Route24.blk");
static ROUTE25_BLK: &[u8] = include_bytes!("../../../../maps/Route25.blk");
static ROUTE2GATE_BLK: &[u8] = include_bytes!("../../../../maps/Route2Gate.blk");
static ROUTE2TRADEHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/Route2TradeHouse.blk");
static ROUTE3_BLK: &[u8] = include_bytes!("../../../../maps/Route3.blk");
static ROUTE4_BLK: &[u8] = include_bytes!("../../../../maps/Route4.blk");
static ROUTE5_BLK: &[u8] = include_bytes!("../../../../maps/Route5.blk");
static ROUTE5GATE_BLK: &[u8] = include_bytes!("../../../../maps/Route5Gate.blk");
static ROUTE6_BLK: &[u8] = include_bytes!("../../../../maps/Route6.blk");
static ROUTE6GATE_BLK: &[u8] = include_bytes!("../../../../maps/Route6Gate.blk");
static ROUTE7_BLK: &[u8] = include_bytes!("../../../../maps/Route7.blk");
static ROUTE7GATE_BLK: &[u8] = include_bytes!("../../../../maps/Route7Gate.blk");
static ROUTE8_BLK: &[u8] = include_bytes!("../../../../maps/Route8.blk");
static ROUTE8GATE_BLK: &[u8] = include_bytes!("../../../../maps/Route8Gate.blk");
static ROUTE9_BLK: &[u8] = include_bytes!("../../../../maps/Route9.blk");
static SSANNE1F_BLK: &[u8] = include_bytes!("../../../../maps/SSAnne1F.blk");
static SSANNE1FROOMS_BLK: &[u8] = include_bytes!("../../../../maps/SSAnne1FRooms.blk");
static SSANNE2F_BLK: &[u8] = include_bytes!("../../../../maps/SSAnne2F.blk");
static SSANNE2FROOMS_BLK: &[u8] = include_bytes!("../../../../maps/SSAnne2FRooms.blk");
static SSANNE3F_BLK: &[u8] = include_bytes!("../../../../maps/SSAnne3F.blk");
static SSANNEB1F_BLK: &[u8] = include_bytes!("../../../../maps/SSAnneB1F.blk");
static SSANNEB1FROOMS_BLK: &[u8] = include_bytes!("../../../../maps/SSAnneB1FRooms.blk");
static SSANNEBOW_BLK: &[u8] = include_bytes!("../../../../maps/SSAnneBow.blk");
static SSANNECAPTAINSROOM_BLK: &[u8] = include_bytes!("../../../../maps/SSAnneCaptainsRoom.blk");
static SSANNEKITCHEN_BLK: &[u8] = include_bytes!("../../../../maps/SSAnneKitchen.blk");
static SAFARIZONECENTER_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneCenter.blk");
static SAFARIZONECENTERRESTHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneCenterRestHouse.blk");
static SAFARIZONEEAST_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneEast.blk");
static SAFARIZONEEASTRESTHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneEastRestHouse.blk");
static SAFARIZONEGATE_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneGate.blk");
static SAFARIZONENORTH_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneNorth.blk");
static SAFARIZONENORTHRESTHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneNorthRestHouse.blk");
static SAFARIZONESECRETHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneSecretHouse.blk");
static SAFARIZONEWEST_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneWest.blk");
static SAFARIZONEWESTRESTHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/SafariZoneWestRestHouse.blk");
static SAFFRONCITY_BLK: &[u8] = include_bytes!("../../../../maps/SaffronCity.blk");
static SAFFRONGYM_BLK: &[u8] = include_bytes!("../../../../maps/SaffronGym.blk");
static SAFFRONMART_BLK: &[u8] = include_bytes!("../../../../maps/SaffronMart.blk");
static SAFFRONPIDGEYHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/SaffronPidgeyHouse.blk");
static SAFFRONPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/SaffronPokecenter.blk");
static SEAFOAMISLANDS1F_BLK: &[u8] = include_bytes!("../../../../maps/SeafoamIslands1F.blk");
static SEAFOAMISLANDSB1F_BLK: &[u8] = include_bytes!("../../../../maps/SeafoamIslandsB1F.blk");
static SEAFOAMISLANDSB2F_BLK: &[u8] = include_bytes!("../../../../maps/SeafoamIslandsB2F.blk");
static SEAFOAMISLANDSB3F_BLK: &[u8] = include_bytes!("../../../../maps/SeafoamIslandsB3F.blk");
static SEAFOAMISLANDSB4F_BLK: &[u8] = include_bytes!("../../../../maps/SeafoamIslandsB4F.blk");
static SILPHCO10F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo10F.blk");
static SILPHCO11F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo11F.blk");
static SILPHCO1F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo1F.blk");
static SILPHCO2F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo2F.blk");
static SILPHCO3F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo3F.blk");
static SILPHCO4F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo4F.blk");
static SILPHCO5F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo5F.blk");
static SILPHCO6F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo6F.blk");
static SILPHCO7F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo7F.blk");
static SILPHCO8F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo8F.blk");
static SILPHCO9F_BLK: &[u8] = include_bytes!("../../../../maps/SilphCo9F.blk");
static SILPHCOELEVATOR_BLK: &[u8] = include_bytes!("../../../../maps/SilphCoElevator.blk");
static TRADECENTER_BLK: &[u8] = include_bytes!("../../../../maps/TradeCenter.blk");
static UNDERGROUNDPATHNORTHSOUTH_BLK: &[u8] = include_bytes!("../../../../maps/UndergroundPathNorthSouth.blk");
static UNDERGROUNDPATHROUTE5_BLK: &[u8] = include_bytes!("../../../../maps/UndergroundPathRoute5.blk");
static UNDERGROUNDPATHROUTE6_BLK: &[u8] = include_bytes!("../../../../maps/UndergroundPathRoute6.blk");
static UNDERGROUNDPATHROUTE7_BLK: &[u8] = include_bytes!("../../../../maps/UndergroundPathRoute7.blk");
static UNDERGROUNDPATHROUTE8_BLK: &[u8] = include_bytes!("../../../../maps/UndergroundPathRoute8.blk");
static UNDERGROUNDPATHWESTEAST_BLK: &[u8] = include_bytes!("../../../../maps/UndergroundPathWestEast.blk");
static VERMILIONCITY_BLK: &[u8] = include_bytes!("../../../../maps/VermilionCity.blk");
static VERMILIONDOCK_BLK: &[u8] = include_bytes!("../../../../maps/VermilionDock.blk");
static VERMILIONGYM_BLK: &[u8] = include_bytes!("../../../../maps/VermilionGym.blk");
static VERMILIONMART_BLK: &[u8] = include_bytes!("../../../../maps/VermilionMart.blk");
static VERMILIONOLDRODHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/VermilionOldRodHouse.blk");
static VERMILIONPIDGEYHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/VermilionPidgeyHouse.blk");
static VERMILIONPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/VermilionPokecenter.blk");
static VERMILIONTRADEHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/VermilionTradeHouse.blk");
static VICTORYROAD1F_BLK: &[u8] = include_bytes!("../../../../maps/VictoryRoad1F.blk");
static VICTORYROAD2F_BLK: &[u8] = include_bytes!("../../../../maps/VictoryRoad2F.blk");
static VICTORYROAD3F_BLK: &[u8] = include_bytes!("../../../../maps/VictoryRoad3F.blk");
static VIRIDIANCITY_BLK: &[u8] = include_bytes!("../../../../maps/ViridianCity.blk");
static VIRIDIANFOREST_BLK: &[u8] = include_bytes!("../../../../maps/ViridianForest.blk");
static VIRIDIANFORESTNORTHGATE_BLK: &[u8] = include_bytes!("../../../../maps/ViridianForestNorthGate.blk");
static VIRIDIANFORESTSOUTHGATE_BLK: &[u8] = include_bytes!("../../../../maps/ViridianForestSouthGate.blk");
static VIRIDIANGYM_BLK: &[u8] = include_bytes!("../../../../maps/ViridianGym.blk");
static VIRIDIANMART_BLK: &[u8] = include_bytes!("../../../../maps/ViridianMart.blk");
static VIRIDIANNICKNAMEHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/ViridianNicknameHouse.blk");
static VIRIDIANPOKECENTER_BLK: &[u8] = include_bytes!("../../../../maps/ViridianPokecenter.blk");
static VIRIDIANSCHOOLHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/ViridianSchoolHouse.blk");
static WARDENSHOUSE_BLK: &[u8] = include_bytes!("../../../../maps/WardensHouse.blk");

pub fn block_data_for_map(map: MapId) -> &'static [u8] {
    match map {
        MapId::PalletTown => PALLETTOWN_BLK,
        MapId::ViridianCity => VIRIDIANCITY_BLK,
        MapId::PewterCity => PEWTERCITY_BLK,
        MapId::CeruleanCity => CERULEANCITY_BLK,
        MapId::LavenderTown => LAVENDERTOWN_BLK,
        MapId::VermilionCity => VERMILIONCITY_BLK,
        MapId::CeladonCity => CELADONCITY_BLK,
        MapId::FuchsiaCity => FUCHSIACITY_BLK,
        MapId::CinnabarIsland => CINNABARISLAND_BLK,
        MapId::IndigoPlateau => INDIGOPLATEAU_BLK,
        MapId::SaffronCity => SAFFRONCITY_BLK,
        MapId::UnusedMap0B => &[],
        MapId::Route1 => ROUTE1_BLK,
        MapId::Route2 => ROUTE2_BLK,
        MapId::Route3 => ROUTE3_BLK,
        MapId::Route4 => ROUTE4_BLK,
        MapId::Route5 => ROUTE5_BLK,
        MapId::Route6 => ROUTE6_BLK,
        MapId::Route7 => ROUTE7_BLK,
        MapId::Route8 => ROUTE8_BLK,
        MapId::Route9 => ROUTE9_BLK,
        MapId::Route10 => ROUTE10_BLK,
        MapId::Route11 => ROUTE11_BLK,
        MapId::Route12 => ROUTE12_BLK,
        MapId::Route13 => ROUTE13_BLK,
        MapId::Route14 => ROUTE14_BLK,
        MapId::Route15 => ROUTE15_BLK,
        MapId::Route16 => ROUTE16_BLK,
        MapId::Route17 => ROUTE17_BLK,
        MapId::Route18 => ROUTE18_BLK,
        MapId::Route19 => ROUTE19_BLK,
        MapId::Route20 => ROUTE20_BLK,
        MapId::Route21 => ROUTE21_BLK,
        MapId::Route22 => ROUTE22_BLK,
        MapId::Route23 => ROUTE23_BLK,
        MapId::Route24 => ROUTE24_BLK,
        MapId::Route25 => ROUTE25_BLK,
        MapId::RedsHouse1F => REDSHOUSE1F_BLK,
        MapId::RedsHouse2F => REDSHOUSE2F_BLK,
        MapId::BluesHouse => BLUESHOUSE_BLK,
        MapId::OaksLab => OAKSLAB_BLK,
        MapId::ViridianPokecenter => VIRIDIANPOKECENTER_BLK,
        MapId::ViridianMart => VIRIDIANMART_BLK,
        MapId::ViridianSchoolHouse => VIRIDIANSCHOOLHOUSE_BLK,
        MapId::ViridianNicknameHouse => VIRIDIANNICKNAMEHOUSE_BLK,
        MapId::ViridianGym => VIRIDIANGYM_BLK,
        MapId::DiglettsCaveRoute2 => DIGLETTSCAVEROUTE2_BLK,
        MapId::ViridianForestNorthGate => VIRIDIANFORESTNORTHGATE_BLK,
        MapId::Route2TradeHouse => ROUTE2TRADEHOUSE_BLK,
        MapId::Route2Gate => ROUTE2GATE_BLK,
        MapId::ViridianForestSouthGate => VIRIDIANFORESTSOUTHGATE_BLK,
        MapId::ViridianForest => VIRIDIANFOREST_BLK,
        MapId::Museum1F => MUSEUM1F_BLK,
        MapId::Museum2F => MUSEUM2F_BLK,
        MapId::PewterGym => PEWTERGYM_BLK,
        MapId::PewterNidoranHouse => PEWTERNIDORANHOUSE_BLK,
        MapId::PewterMart => PEWTERMART_BLK,
        MapId::PewterSpeechHouse => PEWTERSPEECHHOUSE_BLK,
        MapId::PewterPokecenter => PEWTERPOKECENTER_BLK,
        MapId::MtMoon1F => MTMOON1F_BLK,
        MapId::MtMoonB1F => MTMOONB1F_BLK,
        MapId::MtMoonB2F => MTMOONB2F_BLK,
        MapId::CeruleanTrashedHouse => CERULEANTRASHEDHOUSE_BLK,
        MapId::CeruleanTradeHouse => CERULEANTRADEHOUSE_BLK,
        MapId::CeruleanPokecenter => CERULEANPOKECENTER_BLK,
        MapId::CeruleanGym => CERULEANGYM_BLK,
        MapId::BikeShop => BIKESHOP_BLK,
        MapId::CeruleanMart => CERULEANMART_BLK,
        MapId::MtMoonPokecenter => MTMOONPOKECENTER_BLK,
        MapId::CeruleanTrashedHouseCopy => &[],
        MapId::Route5Gate => ROUTE5GATE_BLK,
        MapId::UndergroundPathRoute5 => UNDERGROUNDPATHROUTE5_BLK,
        MapId::Daycare => DAYCARE_BLK,
        MapId::Route6Gate => ROUTE6GATE_BLK,
        MapId::UndergroundPathRoute6 => UNDERGROUNDPATHROUTE6_BLK,
        MapId::UndergroundPathRoute6Copy => &[],
        MapId::Route7Gate => ROUTE7GATE_BLK,
        MapId::UndergroundPathRoute7 => UNDERGROUNDPATHROUTE7_BLK,
        MapId::UndergroundPathRoute7Copy => &[],
        MapId::Route8Gate => ROUTE8GATE_BLK,
        MapId::UndergroundPathRoute8 => UNDERGROUNDPATHROUTE8_BLK,
        MapId::RockTunnelPokecenter => ROCKTUNNELPOKECENTER_BLK,
        MapId::RockTunnel1F => ROCKTUNNEL1F_BLK,
        MapId::PowerPlant => POWERPLANT_BLK,
        MapId::Route11Gate1F => ROUTE11GATE1F_BLK,
        MapId::DiglettsCaveRoute11 => DIGLETTSCAVEROUTE11_BLK,
        MapId::Route11Gate2F => ROUTE11GATE2F_BLK,
        MapId::Route12Gate1F => ROUTE12GATE1F_BLK,
        MapId::BillsHouse => BILLSHOUSE_BLK,
        MapId::VermilionPokecenter => VERMILIONPOKECENTER_BLK,
        MapId::PokemonFanClub => POKEMONFANCLUB_BLK,
        MapId::VermilionMart => VERMILIONMART_BLK,
        MapId::VermilionGym => VERMILIONGYM_BLK,
        MapId::VermilionPidgeyHouse => VERMILIONPIDGEYHOUSE_BLK,
        MapId::VermilionDock => VERMILIONDOCK_BLK,
        MapId::SSAnne1F => SSANNE1F_BLK,
        MapId::SSAnne2F => SSANNE2F_BLK,
        MapId::SSAnne3F => SSANNE3F_BLK,
        MapId::SSAnneB1F => SSANNEB1F_BLK,
        MapId::SSAnneBow => SSANNEBOW_BLK,
        MapId::SSAnneKitchen => SSANNEKITCHEN_BLK,
        MapId::SSAnneCaptainsRoom => SSANNECAPTAINSROOM_BLK,
        MapId::SSAnne1FRooms => SSANNE1FROOMS_BLK,
        MapId::SSAnne2FRooms => SSANNE2FROOMS_BLK,
        MapId::SSAnneB1FRooms => SSANNEB1FROOMS_BLK,
        MapId::UnusedMap69 => &[],
        MapId::UnusedMap6A => &[],
        MapId::UnusedMap6B => &[],
        MapId::VictoryRoad1F => VICTORYROAD1F_BLK,
        MapId::UnusedMap6D => &[],
        MapId::UnusedMap6E => &[],
        MapId::UnusedMap6F => &[],
        MapId::UnusedMap70 => &[],
        MapId::LancesRoom => LANCESROOM_BLK,
        MapId::UnusedMap72 => &[],
        MapId::UnusedMap73 => &[],
        MapId::UnusedMap74 => &[],
        MapId::UnusedMap75 => &[],
        MapId::HallOfFame => HALLOFFAME_BLK,
        MapId::UndergroundPathNorthSouth => UNDERGROUNDPATHNORTHSOUTH_BLK,
        MapId::ChampionsRoom => CHAMPIONSROOM_BLK,
        MapId::UndergroundPathWestEast => UNDERGROUNDPATHWESTEAST_BLK,
        MapId::CeladonMart1F => CELADONMART1F_BLK,
        MapId::CeladonMart2F => CELADONMART2F_BLK,
        MapId::CeladonMart3F => CELADONMART3F_BLK,
        MapId::CeladonMart4F => CELADONMART4F_BLK,
        MapId::CeladonMartRoof => CELADONMARTROOF_BLK,
        MapId::CeladonMartElevator => CELADONMARTELEVATOR_BLK,
        MapId::CeladonMansion1F => CELADONMANSION1F_BLK,
        MapId::CeladonMansion2F => CELADONMANSION2F_BLK,
        MapId::CeladonMansion3F => CELADONMANSION3F_BLK,
        MapId::CeladonMansionRoof => CELADONMANSIONROOF_BLK,
        MapId::CeladonMansionRoofHouse => CELADONMANSIONROOFHOUSE_BLK,
        MapId::CeladonPokecenter => CELADONPOKECENTER_BLK,
        MapId::CeladonGym => CELADONGYM_BLK,
        MapId::GameCorner => GAMECORNER_BLK,
        MapId::CeladonMart5F => CELADONMART5F_BLK,
        MapId::GameCornerPrizeRoom => GAMECORNERPRIZEROOM_BLK,
        MapId::CeladonDiner => CELADONDINER_BLK,
        MapId::CeladonChiefHouse => CELADONCHIEFHOUSE_BLK,
        MapId::CeladonHotel => CELADONHOTEL_BLK,
        MapId::LavenderPokecenter => LAVENDERPOKECENTER_BLK,
        MapId::PokemonTower1F => POKEMONTOWER1F_BLK,
        MapId::PokemonTower2F => POKEMONTOWER2F_BLK,
        MapId::PokemonTower3F => POKEMONTOWER3F_BLK,
        MapId::PokemonTower4F => POKEMONTOWER4F_BLK,
        MapId::PokemonTower5F => POKEMONTOWER5F_BLK,
        MapId::PokemonTower6F => POKEMONTOWER6F_BLK,
        MapId::PokemonTower7F => POKEMONTOWER7F_BLK,
        MapId::MrFujisHouse => MRFUJISHOUSE_BLK,
        MapId::LavenderMart => LAVENDERMART_BLK,
        MapId::LavenderCuboneHouse => LAVENDERCUBONEHOUSE_BLK,
        MapId::FuchsiaMart => FUCHSIAMART_BLK,
        MapId::FuchsiaBillsGrandpasHouse => FUCHSIABILLSGRANDPASHOUSE_BLK,
        MapId::FuchsiaPokecenter => FUCHSIAPOKECENTER_BLK,
        MapId::WardensHouse => WARDENSHOUSE_BLK,
        MapId::SafariZoneGate => SAFARIZONEGATE_BLK,
        MapId::FuchsiaGym => FUCHSIAGYM_BLK,
        MapId::FuchsiaMeetingRoom => FUCHSIAMEETINGROOM_BLK,
        MapId::SeafoamIslandsB1F => SEAFOAMISLANDSB1F_BLK,
        MapId::SeafoamIslandsB2F => SEAFOAMISLANDSB2F_BLK,
        MapId::SeafoamIslandsB3F => SEAFOAMISLANDSB3F_BLK,
        MapId::SeafoamIslandsB4F => SEAFOAMISLANDSB4F_BLK,
        MapId::VermilionOldRodHouse => VERMILIONOLDRODHOUSE_BLK,
        MapId::FuchsiaGoodRodHouse => FUCHSIAGOODRODHOUSE_BLK,
        MapId::PokemonMansion1F => POKEMONMANSION1F_BLK,
        MapId::CinnabarGym => CINNABARGYM_BLK,
        MapId::CinnabarLab => CINNABARLAB_BLK,
        MapId::CinnabarLabTradeRoom => CINNABARLABTRADEROOM_BLK,
        MapId::CinnabarLabMetronomeRoom => CINNABARLABMETRONOMEROOM_BLK,
        MapId::CinnabarLabFossilRoom => CINNABARLABFOSSILROOM_BLK,
        MapId::CinnabarPokecenter => CINNABARPOKECENTER_BLK,
        MapId::CinnabarMart => CINNABARMART_BLK,
        MapId::CinnabarMartCopy => &[],
        MapId::IndigoPlateauLobby => INDIGOPLATEAULOBBY_BLK,
        MapId::CopycatsHouse1F => COPYCATSHOUSE1F_BLK,
        MapId::CopycatsHouse2F => COPYCATSHOUSE2F_BLK,
        MapId::FightingDojo => FIGHTINGDOJO_BLK,
        MapId::SaffronGym => SAFFRONGYM_BLK,
        MapId::SaffronPidgeyHouse => SAFFRONPIDGEYHOUSE_BLK,
        MapId::SaffronMart => SAFFRONMART_BLK,
        MapId::SilphCo1F => SILPHCO1F_BLK,
        MapId::SaffronPokecenter => SAFFRONPOKECENTER_BLK,
        MapId::MrPsychicsHouse => MRPSYCHICSHOUSE_BLK,
        MapId::Route15Gate1F => ROUTE15GATE1F_BLK,
        MapId::Route15Gate2F => ROUTE15GATE2F_BLK,
        MapId::Route16Gate1F => ROUTE16GATE1F_BLK,
        MapId::Route16Gate2F => ROUTE16GATE2F_BLK,
        MapId::Route16FlyHouse => ROUTE16FLYHOUSE_BLK,
        MapId::Route12SuperRodHouse => ROUTE12SUPERRODHOUSE_BLK,
        MapId::Route18Gate1F => ROUTE18GATE1F_BLK,
        MapId::Route18Gate2F => ROUTE18GATE2F_BLK,
        MapId::SeafoamIslands1F => SEAFOAMISLANDS1F_BLK,
        MapId::Route22Gate => ROUTE22GATE_BLK,
        MapId::VictoryRoad2F => VICTORYROAD2F_BLK,
        MapId::Route12Gate2F => ROUTE12GATE2F_BLK,
        MapId::VermilionTradeHouse => VERMILIONTRADEHOUSE_BLK,
        MapId::DiglettsCave => DIGLETTSCAVE_BLK,
        MapId::VictoryRoad3F => VICTORYROAD3F_BLK,
        MapId::RocketHideoutB1F => ROCKETHIDEOUTB1F_BLK,
        MapId::RocketHideoutB2F => ROCKETHIDEOUTB2F_BLK,
        MapId::RocketHideoutB3F => ROCKETHIDEOUTB3F_BLK,
        MapId::RocketHideoutB4F => ROCKETHIDEOUTB4F_BLK,
        MapId::RocketHideoutElevator => ROCKETHIDEOUTELEVATOR_BLK,
        MapId::UnusedMapCC => &[],
        MapId::UnusedMapCD => &[],
        MapId::UnusedMapCE => &[],
        MapId::SilphCo2F => SILPHCO2F_BLK,
        MapId::SilphCo3F => SILPHCO3F_BLK,
        MapId::SilphCo4F => SILPHCO4F_BLK,
        MapId::SilphCo5F => SILPHCO5F_BLK,
        MapId::SilphCo6F => SILPHCO6F_BLK,
        MapId::SilphCo7F => SILPHCO7F_BLK,
        MapId::SilphCo8F => SILPHCO8F_BLK,
        MapId::PokemonMansion2F => POKEMONMANSION2F_BLK,
        MapId::PokemonMansion3F => POKEMONMANSION3F_BLK,
        MapId::PokemonMansionB1F => POKEMONMANSIONB1F_BLK,
        MapId::SafariZoneEast => SAFARIZONEEAST_BLK,
        MapId::SafariZoneNorth => SAFARIZONENORTH_BLK,
        MapId::SafariZoneWest => SAFARIZONEWEST_BLK,
        MapId::SafariZoneCenter => SAFARIZONECENTER_BLK,
        MapId::SafariZoneCenterRestHouse => SAFARIZONECENTERRESTHOUSE_BLK,
        MapId::SafariZoneSecretHouse => SAFARIZONESECRETHOUSE_BLK,
        MapId::SafariZoneWestRestHouse => SAFARIZONEWESTRESTHOUSE_BLK,
        MapId::SafariZoneEastRestHouse => SAFARIZONEEASTRESTHOUSE_BLK,
        MapId::SafariZoneNorthRestHouse => SAFARIZONENORTHRESTHOUSE_BLK,
        MapId::CeruleanCave2F => CERULEANCAVE2F_BLK,
        MapId::CeruleanCaveB1F => CERULEANCAVEB1F_BLK,
        MapId::CeruleanCave1F => CERULEANCAVE1F_BLK,
        MapId::NameRatersHouse => NAMERATERSHOUSE_BLK,
        MapId::CeruleanBadgeHouse => CERULEANBADGEHOUSE_BLK,
        MapId::UnusedMapE7 => &[],
        MapId::RockTunnelB1F => ROCKTUNNELB1F_BLK,
        MapId::SilphCo9F => SILPHCO9F_BLK,
        MapId::SilphCo10F => SILPHCO10F_BLK,
        MapId::SilphCo11F => SILPHCO11F_BLK,
        MapId::SilphCoElevator => SILPHCOELEVATOR_BLK,
        MapId::UnusedMapED => &[],
        MapId::UnusedMapEE => &[],
        MapId::TradeCenter => TRADECENTER_BLK,
        MapId::Colosseum => COLOSSEUM_BLK,
        MapId::UnusedMapF1 => &[],
        MapId::UnusedMapF2 => &[],
        MapId::UnusedMapF3 => &[],
        MapId::UnusedMapF4 => &[],
        MapId::LoreleisRoom => LORELEISROOM_BLK,
        MapId::BrunosRoom => BRUNOSROOM_BLK,
        MapId::AgathasRoom => AGATHASROOM_BLK,
    }
}

