use serde::{Deserialize, Serialize};
use crate::moves::{MoveId, MoveEffect};
use crate::types::PokemonType;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct MoveData {
    pub id: MoveId,
    pub effect: MoveEffect,
    pub power: u8,
    pub move_type: PokemonType,
    pub accuracy: u8,
    pub pp: u8,
}

pub const MOVES: [MoveData; 165] = [
    MoveData { id: MoveId::Pound, effect: MoveEffect::NoAdditionalEffect, power: 40, move_type: PokemonType::Normal, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::KarateChop, effect: MoveEffect::NoAdditionalEffect, power: 50, move_type: PokemonType::Normal, accuracy: 100, pp: 25 },
    MoveData { id: MoveId::Doubleslap, effect: MoveEffect::TwoToFiveAttacksEffect, power: 15, move_type: PokemonType::Normal, accuracy: 85, pp: 10 },
    MoveData { id: MoveId::CometPunch, effect: MoveEffect::TwoToFiveAttacksEffect, power: 18, move_type: PokemonType::Normal, accuracy: 85, pp: 15 },
    MoveData { id: MoveId::MegaPunch, effect: MoveEffect::NoAdditionalEffect, power: 80, move_type: PokemonType::Normal, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::PayDay, effect: MoveEffect::PayDayEffect, power: 40, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::FirePunch, effect: MoveEffect::BurnSideEffect1, power: 75, move_type: PokemonType::Fire, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::IcePunch, effect: MoveEffect::FreezeSideEffect1, power: 75, move_type: PokemonType::Ice, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Thunderpunch, effect: MoveEffect::ParalyzeSideEffect1, power: 75, move_type: PokemonType::Electric, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Scratch, effect: MoveEffect::NoAdditionalEffect, power: 40, move_type: PokemonType::Normal, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::Vicegrip, effect: MoveEffect::NoAdditionalEffect, power: 55, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Guillotine, effect: MoveEffect::OhkoEffect, power: 1, move_type: PokemonType::Normal, accuracy: 30, pp: 5 },
    MoveData { id: MoveId::RazorWind, effect: MoveEffect::ChargeEffect, power: 80, move_type: PokemonType::Normal, accuracy: 75, pp: 10 },
    MoveData { id: MoveId::SwordsDance, effect: MoveEffect::AttackUp2Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Cut, effect: MoveEffect::NoAdditionalEffect, power: 50, move_type: PokemonType::Normal, accuracy: 95, pp: 30 },
    MoveData { id: MoveId::Gust, effect: MoveEffect::NoAdditionalEffect, power: 40, move_type: PokemonType::Normal, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::WingAttack, effect: MoveEffect::NoAdditionalEffect, power: 35, move_type: PokemonType::Flying, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::Whirlwind, effect: MoveEffect::SwitchAndTeleportEffect, power: 0, move_type: PokemonType::Normal, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::Fly, effect: MoveEffect::FlyEffect, power: 70, move_type: PokemonType::Flying, accuracy: 95, pp: 15 },
    MoveData { id: MoveId::Bind, effect: MoveEffect::TrappingEffect, power: 15, move_type: PokemonType::Normal, accuracy: 75, pp: 20 },
    MoveData { id: MoveId::Slam, effect: MoveEffect::NoAdditionalEffect, power: 80, move_type: PokemonType::Normal, accuracy: 75, pp: 20 },
    MoveData { id: MoveId::VineWhip, effect: MoveEffect::NoAdditionalEffect, power: 35, move_type: PokemonType::Grass, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Stomp, effect: MoveEffect::FlinchSideEffect2, power: 65, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::DoubleKick, effect: MoveEffect::AttackTwiceEffect, power: 30, move_type: PokemonType::Fighting, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::MegaKick, effect: MoveEffect::NoAdditionalEffect, power: 120, move_type: PokemonType::Normal, accuracy: 75, pp: 5 },
    MoveData { id: MoveId::JumpKick, effect: MoveEffect::JumpKickEffect, power: 70, move_type: PokemonType::Fighting, accuracy: 95, pp: 25 },
    MoveData { id: MoveId::RollingKick, effect: MoveEffect::FlinchSideEffect2, power: 60, move_type: PokemonType::Fighting, accuracy: 85, pp: 15 },
    MoveData { id: MoveId::SandAttack, effect: MoveEffect::AccuracyDown1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Headbutt, effect: MoveEffect::FlinchSideEffect2, power: 70, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::HornAttack, effect: MoveEffect::NoAdditionalEffect, power: 65, move_type: PokemonType::Normal, accuracy: 100, pp: 25 },
    MoveData { id: MoveId::FuryAttack, effect: MoveEffect::TwoToFiveAttacksEffect, power: 15, move_type: PokemonType::Normal, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::HornDrill, effect: MoveEffect::OhkoEffect, power: 1, move_type: PokemonType::Normal, accuracy: 30, pp: 5 },
    MoveData { id: MoveId::Tackle, effect: MoveEffect::NoAdditionalEffect, power: 35, move_type: PokemonType::Normal, accuracy: 95, pp: 35 },
    MoveData { id: MoveId::BodySlam, effect: MoveEffect::ParalyzeSideEffect2, power: 85, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Wrap, effect: MoveEffect::TrappingEffect, power: 15, move_type: PokemonType::Normal, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::TakeDown, effect: MoveEffect::RecoilEffect, power: 90, move_type: PokemonType::Normal, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::Thrash, effect: MoveEffect::ThrashPetalDanceEffect, power: 90, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::DoubleEdge, effect: MoveEffect::RecoilEffect, power: 100, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::TailWhip, effect: MoveEffect::DefenseDown1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::PoisonSting, effect: MoveEffect::PoisonSideEffect1, power: 15, move_type: PokemonType::Poison, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::Twineedle, effect: MoveEffect::TwineedleEffect, power: 25, move_type: PokemonType::Bug, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::PinMissile, effect: MoveEffect::TwoToFiveAttacksEffect, power: 14, move_type: PokemonType::Bug, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::Leer, effect: MoveEffect::DefenseDown1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Bite, effect: MoveEffect::FlinchSideEffect1, power: 60, move_type: PokemonType::Normal, accuracy: 100, pp: 25 },
    MoveData { id: MoveId::Growl, effect: MoveEffect::AttackDown1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::Roar, effect: MoveEffect::SwitchAndTeleportEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Sing, effect: MoveEffect::SleepEffect, power: 0, move_type: PokemonType::Normal, accuracy: 55, pp: 15 },
    MoveData { id: MoveId::Supersonic, effect: MoveEffect::ConfusionEffect, power: 0, move_type: PokemonType::Normal, accuracy: 55, pp: 20 },
    MoveData { id: MoveId::Sonicboom, effect: MoveEffect::SpecialDamageEffect, power: 1, move_type: PokemonType::Normal, accuracy: 90, pp: 20 },
    MoveData { id: MoveId::Disable, effect: MoveEffect::DisableEffect, power: 0, move_type: PokemonType::Normal, accuracy: 55, pp: 20 },
    MoveData { id: MoveId::Acid, effect: MoveEffect::DefenseDownSideEffect, power: 40, move_type: PokemonType::Poison, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Ember, effect: MoveEffect::BurnSideEffect1, power: 40, move_type: PokemonType::Fire, accuracy: 100, pp: 25 },
    MoveData { id: MoveId::Flamethrower, effect: MoveEffect::BurnSideEffect1, power: 95, move_type: PokemonType::Fire, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Mist, effect: MoveEffect::MistEffect, power: 0, move_type: PokemonType::Ice, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::WaterGun, effect: MoveEffect::NoAdditionalEffect, power: 40, move_type: PokemonType::Water, accuracy: 100, pp: 25 },
    MoveData { id: MoveId::HydroPump, effect: MoveEffect::NoAdditionalEffect, power: 120, move_type: PokemonType::Water, accuracy: 80, pp: 5 },
    MoveData { id: MoveId::Surf, effect: MoveEffect::NoAdditionalEffect, power: 95, move_type: PokemonType::Water, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::IceBeam, effect: MoveEffect::FreezeSideEffect1, power: 95, move_type: PokemonType::Ice, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Blizzard, effect: MoveEffect::FreezeSideEffect1, power: 120, move_type: PokemonType::Ice, accuracy: 90, pp: 5 },
    MoveData { id: MoveId::Psybeam, effect: MoveEffect::ConfusionSideEffect, power: 65, move_type: PokemonType::Psychic, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Bubblebeam, effect: MoveEffect::SpeedDownSideEffect, power: 65, move_type: PokemonType::Water, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::AuroraBeam, effect: MoveEffect::AttackDownSideEffect, power: 65, move_type: PokemonType::Ice, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::HyperBeam, effect: MoveEffect::HyperBeamEffect, power: 150, move_type: PokemonType::Normal, accuracy: 90, pp: 5 },
    MoveData { id: MoveId::Peck, effect: MoveEffect::NoAdditionalEffect, power: 35, move_type: PokemonType::Flying, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::DrillPeck, effect: MoveEffect::NoAdditionalEffect, power: 80, move_type: PokemonType::Flying, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Submission, effect: MoveEffect::RecoilEffect, power: 80, move_type: PokemonType::Fighting, accuracy: 80, pp: 25 },
    MoveData { id: MoveId::LowKick, effect: MoveEffect::FlinchSideEffect2, power: 50, move_type: PokemonType::Fighting, accuracy: 90, pp: 20 },
    MoveData { id: MoveId::Counter, effect: MoveEffect::NoAdditionalEffect, power: 1, move_type: PokemonType::Fighting, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::SeismicToss, effect: MoveEffect::SpecialDamageEffect, power: 1, move_type: PokemonType::Fighting, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Strength, effect: MoveEffect::NoAdditionalEffect, power: 80, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Absorb, effect: MoveEffect::DrainHpEffect, power: 20, move_type: PokemonType::Grass, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::MegaDrain, effect: MoveEffect::DrainHpEffect, power: 40, move_type: PokemonType::Grass, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::LeechSeed, effect: MoveEffect::LeechSeedEffect, power: 0, move_type: PokemonType::Grass, accuracy: 90, pp: 10 },
    MoveData { id: MoveId::Growth, effect: MoveEffect::SpecialUp1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::RazorLeaf, effect: MoveEffect::NoAdditionalEffect, power: 55, move_type: PokemonType::Grass, accuracy: 95, pp: 25 },
    MoveData { id: MoveId::Solarbeam, effect: MoveEffect::ChargeEffect, power: 120, move_type: PokemonType::Grass, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Poisonpowder, effect: MoveEffect::PoisonEffect, power: 0, move_type: PokemonType::Poison, accuracy: 75, pp: 35 },
    MoveData { id: MoveId::StunSpore, effect: MoveEffect::ParalyzeEffect, power: 0, move_type: PokemonType::Grass, accuracy: 75, pp: 30 },
    MoveData { id: MoveId::SleepPowder, effect: MoveEffect::SleepEffect, power: 0, move_type: PokemonType::Grass, accuracy: 75, pp: 15 },
    MoveData { id: MoveId::PetalDance, effect: MoveEffect::ThrashPetalDanceEffect, power: 70, move_type: PokemonType::Grass, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::StringShot, effect: MoveEffect::SpeedDown1Effect, power: 0, move_type: PokemonType::Bug, accuracy: 95, pp: 40 },
    MoveData { id: MoveId::DragonRage, effect: MoveEffect::SpecialDamageEffect, power: 1, move_type: PokemonType::Dragon, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::FireSpin, effect: MoveEffect::TrappingEffect, power: 15, move_type: PokemonType::Fire, accuracy: 70, pp: 15 },
    MoveData { id: MoveId::Thundershock, effect: MoveEffect::ParalyzeSideEffect1, power: 40, move_type: PokemonType::Electric, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Thunderbolt, effect: MoveEffect::ParalyzeSideEffect1, power: 95, move_type: PokemonType::Electric, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::ThunderWave, effect: MoveEffect::ParalyzeEffect, power: 0, move_type: PokemonType::Electric, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Thunder, effect: MoveEffect::ParalyzeSideEffect1, power: 120, move_type: PokemonType::Electric, accuracy: 70, pp: 10 },
    MoveData { id: MoveId::RockThrow, effect: MoveEffect::NoAdditionalEffect, power: 50, move_type: PokemonType::Rock, accuracy: 65, pp: 15 },
    MoveData { id: MoveId::Earthquake, effect: MoveEffect::NoAdditionalEffect, power: 100, move_type: PokemonType::Ground, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Fissure, effect: MoveEffect::OhkoEffect, power: 1, move_type: PokemonType::Ground, accuracy: 30, pp: 5 },
    MoveData { id: MoveId::Dig, effect: MoveEffect::ChargeEffect, power: 100, move_type: PokemonType::Ground, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Toxic, effect: MoveEffect::PoisonEffect, power: 0, move_type: PokemonType::Poison, accuracy: 85, pp: 10 },
    MoveData { id: MoveId::Confusion, effect: MoveEffect::ConfusionSideEffect, power: 50, move_type: PokemonType::Psychic, accuracy: 100, pp: 25 },
    MoveData { id: MoveId::PsychicM, effect: MoveEffect::SpecialDownSideEffect, power: 90, move_type: PokemonType::Psychic, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Hypnosis, effect: MoveEffect::SleepEffect, power: 0, move_type: PokemonType::Psychic, accuracy: 60, pp: 20 },
    MoveData { id: MoveId::Meditate, effect: MoveEffect::AttackUp1Effect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::Agility, effect: MoveEffect::SpeedUp2Effect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::QuickAttack, effect: MoveEffect::NoAdditionalEffect, power: 40, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Rage, effect: MoveEffect::RageEffect, power: 20, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Teleport, effect: MoveEffect::SwitchAndTeleportEffect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::NightShade, effect: MoveEffect::SpecialDamageEffect, power: 0, move_type: PokemonType::Ghost, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Mimic, effect: MoveEffect::MimicEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Screech, effect: MoveEffect::DefenseDown2Effect, power: 0, move_type: PokemonType::Normal, accuracy: 85, pp: 40 },
    MoveData { id: MoveId::DoubleTeam, effect: MoveEffect::EvasionUp1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Recover, effect: MoveEffect::HealEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Harden, effect: MoveEffect::DefenseUp1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Minimize, effect: MoveEffect::EvasionUp1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Smokescreen, effect: MoveEffect::AccuracyDown1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::ConfuseRay, effect: MoveEffect::ConfusionEffect, power: 0, move_type: PokemonType::Ghost, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Withdraw, effect: MoveEffect::DefenseUp1Effect, power: 0, move_type: PokemonType::Water, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::DefenseCurl, effect: MoveEffect::DefenseUp1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::Barrier, effect: MoveEffect::DefenseUp2Effect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::LightScreen, effect: MoveEffect::LightScreenEffect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Haze, effect: MoveEffect::HazeEffect, power: 0, move_type: PokemonType::Ice, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Reflect, effect: MoveEffect::ReflectEffect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::FocusEnergy, effect: MoveEffect::FocusEnergyEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Bide, effect: MoveEffect::BideEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Metronome, effect: MoveEffect::MetronomeEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::MirrorMove, effect: MoveEffect::MirrorMoveEffect, power: 0, move_type: PokemonType::Flying, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Selfdestruct, effect: MoveEffect::ExplodeEffect, power: 130, move_type: PokemonType::Normal, accuracy: 100, pp: 5 },
    MoveData { id: MoveId::EggBomb, effect: MoveEffect::NoAdditionalEffect, power: 100, move_type: PokemonType::Normal, accuracy: 75, pp: 10 },
    MoveData { id: MoveId::Lick, effect: MoveEffect::ParalyzeSideEffect2, power: 20, move_type: PokemonType::Ghost, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Smog, effect: MoveEffect::PoisonSideEffect2, power: 20, move_type: PokemonType::Poison, accuracy: 70, pp: 20 },
    MoveData { id: MoveId::Sludge, effect: MoveEffect::PoisonSideEffect2, power: 65, move_type: PokemonType::Poison, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::BoneClub, effect: MoveEffect::FlinchSideEffect1, power: 65, move_type: PokemonType::Ground, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::FireBlast, effect: MoveEffect::BurnSideEffect2, power: 120, move_type: PokemonType::Fire, accuracy: 85, pp: 5 },
    MoveData { id: MoveId::Waterfall, effect: MoveEffect::NoAdditionalEffect, power: 80, move_type: PokemonType::Water, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Clamp, effect: MoveEffect::TrappingEffect, power: 35, move_type: PokemonType::Water, accuracy: 75, pp: 10 },
    MoveData { id: MoveId::Swift, effect: MoveEffect::SwiftEffect, power: 60, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::SkullBash, effect: MoveEffect::ChargeEffect, power: 100, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::SpikeCannon, effect: MoveEffect::TwoToFiveAttacksEffect, power: 20, move_type: PokemonType::Normal, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Constrict, effect: MoveEffect::SpeedDownSideEffect, power: 10, move_type: PokemonType::Normal, accuracy: 100, pp: 35 },
    MoveData { id: MoveId::Amnesia, effect: MoveEffect::SpecialUp2Effect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Kinesis, effect: MoveEffect::AccuracyDown1Effect, power: 0, move_type: PokemonType::Psychic, accuracy: 80, pp: 15 },
    MoveData { id: MoveId::Softboiled, effect: MoveEffect::HealEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::HiJumpKick, effect: MoveEffect::JumpKickEffect, power: 85, move_type: PokemonType::Fighting, accuracy: 90, pp: 20 },
    MoveData { id: MoveId::Glare, effect: MoveEffect::ParalyzeEffect, power: 0, move_type: PokemonType::Normal, accuracy: 75, pp: 30 },
    MoveData { id: MoveId::DreamEater, effect: MoveEffect::DreamEaterEffect, power: 100, move_type: PokemonType::Psychic, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::PoisonGas, effect: MoveEffect::PoisonEffect, power: 0, move_type: PokemonType::Poison, accuracy: 55, pp: 40 },
    MoveData { id: MoveId::Barrage, effect: MoveEffect::TwoToFiveAttacksEffect, power: 15, move_type: PokemonType::Normal, accuracy: 85, pp: 20 },
    MoveData { id: MoveId::LeechLife, effect: MoveEffect::DrainHpEffect, power: 20, move_type: PokemonType::Bug, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::LovelyKiss, effect: MoveEffect::SleepEffect, power: 0, move_type: PokemonType::Normal, accuracy: 75, pp: 10 },
    MoveData { id: MoveId::SkyAttack, effect: MoveEffect::ChargeEffect, power: 140, move_type: PokemonType::Flying, accuracy: 90, pp: 5 },
    MoveData { id: MoveId::Transform, effect: MoveEffect::TransformEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Bubble, effect: MoveEffect::SpeedDownSideEffect, power: 20, move_type: PokemonType::Water, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::DizzyPunch, effect: MoveEffect::NoAdditionalEffect, power: 70, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Spore, effect: MoveEffect::SleepEffect, power: 0, move_type: PokemonType::Grass, accuracy: 100, pp: 15 },
    MoveData { id: MoveId::Flash, effect: MoveEffect::AccuracyDown1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 70, pp: 20 },
    MoveData { id: MoveId::Psywave, effect: MoveEffect::SpecialDamageEffect, power: 1, move_type: PokemonType::Psychic, accuracy: 80, pp: 15 },
    MoveData { id: MoveId::Splash, effect: MoveEffect::SplashEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::AcidArmor, effect: MoveEffect::DefenseUp2Effect, power: 0, move_type: PokemonType::Poison, accuracy: 100, pp: 40 },
    MoveData { id: MoveId::Crabhammer, effect: MoveEffect::NoAdditionalEffect, power: 90, move_type: PokemonType::Water, accuracy: 85, pp: 10 },
    MoveData { id: MoveId::Explosion, effect: MoveEffect::ExplodeEffect, power: 170, move_type: PokemonType::Normal, accuracy: 100, pp: 5 },
    MoveData { id: MoveId::FurySwipes, effect: MoveEffect::TwoToFiveAttacksEffect, power: 18, move_type: PokemonType::Normal, accuracy: 80, pp: 15 },
    MoveData { id: MoveId::Bonemerang, effect: MoveEffect::AttackTwiceEffect, power: 50, move_type: PokemonType::Ground, accuracy: 90, pp: 10 },
    MoveData { id: MoveId::Rest, effect: MoveEffect::HealEffect, power: 0, move_type: PokemonType::Psychic, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::RockSlide, effect: MoveEffect::NoAdditionalEffect, power: 75, move_type: PokemonType::Rock, accuracy: 90, pp: 10 },
    MoveData { id: MoveId::HyperFang, effect: MoveEffect::FlinchSideEffect1, power: 80, move_type: PokemonType::Normal, accuracy: 90, pp: 15 },
    MoveData { id: MoveId::Sharpen, effect: MoveEffect::AttackUp1Effect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::Conversion, effect: MoveEffect::ConversionEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 30 },
    MoveData { id: MoveId::TriAttack, effect: MoveEffect::NoAdditionalEffect, power: 80, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::SuperFang, effect: MoveEffect::SuperFangEffect, power: 1, move_type: PokemonType::Normal, accuracy: 90, pp: 10 },
    MoveData { id: MoveId::Slash, effect: MoveEffect::NoAdditionalEffect, power: 70, move_type: PokemonType::Normal, accuracy: 100, pp: 20 },
    MoveData { id: MoveId::Substitute, effect: MoveEffect::SubstituteEffect, power: 0, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
    MoveData { id: MoveId::Struggle, effect: MoveEffect::RecoilEffect, power: 50, move_type: PokemonType::Normal, accuracy: 100, pp: 10 },
];

impl MoveData {
    pub fn get(id: MoveId) -> Option<&'static MoveData> {
        let idx = id as usize;
        if idx == 0 || idx > MOVES.len() {
            None
        } else {
            Some(&MOVES[idx - 1])
        }
    }
}
