use crate::npc_data::{NpcEntry, NpcMovement, NpcFacing};

pub static NPCS_ROUTE8GATE: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x31, x: 2, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE9: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x06, x: 13, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 6, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 24, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 5, trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 31, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 5, trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 48, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 6, trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E, x: 16, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 9, trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E, x: 43, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 6,
        is_trainer: true,
        trainer_class: 9, trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 22, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: true,
        trainer_class: 2, trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E, x: 45, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 8,
        is_trainer: true,
        trainer_class: 9, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 40, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 9,
        is_trainer: true,
        trainer_class: 2, trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 10, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xE6,
    },
];

pub static NPCS_SSANNE1F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x1A, x: 12, y: 6,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 27, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNE1FROOMS: [NpcEntry; 11] = [
    NpcEntry {
        sprite_id: 0x10, x: 2, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 41, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 11, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 41, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 11, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 1, trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 13, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 3, trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D, x: 22, y: 3,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0A, x: 0, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x08, x: 2, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x38, x: 3, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D, x: 10, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 12, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xD0,
    },
    NpcEntry {
        sprite_id: 0x10, x: 21, y: 13,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNE2F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x1A, x: 3, y: 7,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x02, x: 36, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 25, trainer_set: 1,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNE2FROOMS: [NpcEntry; 13] = [
    NpcEntry {
        sprite_id: 0x10, x: 10, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 41, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F, x: 13, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 14, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 0, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 41, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 2, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 3, trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 1, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 12, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x51,
    },
    NpcEntry {
        sprite_id: 0x10, x: 21, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x25, x: 22, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 0, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x10, x: 12, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x35, x: 11, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1D, x: 22, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 12,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F, x: 20, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 13,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNE3F: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x13, x: 9, y: 3,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNEB1F: [NpcEntry; 0] = [];

pub static NPCS_SSANNEB1FROOMS: [NpcEntry; 11] = [
    NpcEntry {
        sprite_id: 0x13, x: 0, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 4, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 2, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 4, trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 12, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 4, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 22, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 4, trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 0, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 4, trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F, x: 0, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 6,
        is_trainer: true,
        trainer_class: 14, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C, x: 10, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x05, x: 11, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 20, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x50,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 10, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xF4,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 12, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x11,
    },
];

pub static NPCS_SSANNEBOW: [NpcEntry; 5] = [
    NpcEntry {
        sprite_id: 0x0C, x: 5, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 4, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 7, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 4, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 4, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 10, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 4, trainer_set: 2,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNECAPTAINSROOM: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x2E, x: 4, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SSANNEKITCHEN: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x14, x: 1, y: 8,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x14, x: 5, y: 8,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x14, x: 9, y: 7,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x14, x: 13, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x14, x: 13, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x14, x: 13, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x14, x: 11, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFARIZONECENTER: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x3D, x: 14, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x31,
    },
];

pub static NPCS_SAFARIZONECENTERRESTHOUSE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x0D, x: 3, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 1, y: 4,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFARIZONEEAST: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x3D, x: 21, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x10,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 3, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x11,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 20, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x26,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 15, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xED,
    },
];

pub static NPCS_SAFARIZONEEASTRESTHOUSE: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x20, x: 1, y: 3,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21, x: 4, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C, x: 5, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFARIZONEGATE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x23, x: 6, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x23, x: 1, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFARIZONENORTH: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x3D, x: 25, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x24,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 19, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xF0,
    },
];

pub static NPCS_SAFARIZONENORTHRESTHOUSE: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x20, x: 6, y: 3,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x23, x: 3, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 1, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFARIZONESECRETHOUSE: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x27, x: 3, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFARIZONEWEST: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x3D, x: 8, y: 20,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x11,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 9, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xE8,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 18, y: 18,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x36,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 19, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x40,
    },
];

pub static NPCS_SAFARIZONEWESTRESTHOUSE: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x20, x: 4, y: 4,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 0, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B, x: 6, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFFRONCITY: [NpcEntry; 15] = [
    NpcEntry {
        sprite_id: 0x18, x: 7, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 20, y: 8,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 34, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 13, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 11, y: 25,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 32, y: 13,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 18, y: 30,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 8, y: 14,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C, x: 23, y: 23,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B, x: 17, y: 30,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 30, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09, x: 31, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 12,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21, x: 18, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 13,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 18, y: 22,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 14,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 19, y: 22,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 15,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFFRONGYM: [NpcEntry; 9] = [
    NpcEntry {
        sprite_id: 0x0D, x: 9, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 40, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x19, x: 10, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 45, trainer_set: 22,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 17, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 19, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x19, x: 3, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 45, trainer_set: 23,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 17, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 19, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x19, x: 3, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: true,
        trainer_class: 45, trainer_set: 24,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 17, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: true,
        trainer_class: 19, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 3, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: true,
        trainer_class: 19, trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x24, x: 10, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFFRONMART: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x26, x: 0, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C, x: 4, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 6, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFFRONPIDGEYHOUSE: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x1D, x: 2, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09, x: 0, y: 4,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 4, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x40, x: 3, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SAFFRONPOKECENTER: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x29, x: 3, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F, x: 5, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 8, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2A, x: 11, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SEAFOAMISLANDS1F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x3F, x: 18, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 26, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SEAFOAMISLANDSB1F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x3F, x: 17, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 22, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SEAFOAMISLANDSB2F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x3F, x: 18, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 23, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SEAFOAMISLANDSB3F: [NpcEntry; 6] = [
    NpcEntry {
        sprite_id: 0x3F, x: 5, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 3, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 8, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 9, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 18, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 19, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SEAFOAMISLANDSB4F: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x3F, x: 4, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 5, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09, x: 6, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCO10F: [NpcEntry; 6] = [
    NpcEntry {
        sprite_id: 0x18, x: 1, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 30, trainer_set: 39,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 10, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 28, trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B, x: 9, y: 15,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 2, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xE2,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 4, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 5, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x26,
    },
];

pub static NPCS_SILPHCO11F: [NpcEntry; 5] = [
    NpcEntry {
        sprite_id: 0x2B, x: 7, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F, x: 10, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x17, x: 6, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 29, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 3, y: 16,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 30, trainer_set: 41,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 15, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 30, trainer_set: 40,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCO1F: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x2A, x: 4, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCO2F: [NpcEntry; 5] = [
    NpcEntry {
        sprite_id: 0x1B, x: 10, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 5, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 28, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 24, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 28, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 16, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 30, trainer_set: 23,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 24, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 30, trainer_set: 24,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCO3F: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x2C, x: 24, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 20, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 30, trainer_set: 25,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 7, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 28, trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 8, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x12,
    },
];

pub static NPCS_SILPHCO4F: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x2C, x: 6, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 9, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 30, trainer_set: 26,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 14, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 28, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 26, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 30, trainer_set: 27,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 3, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x34,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 4, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x36,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 5, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x1D,
    },
];

pub static NPCS_SILPHCO5F: [NpcEntry; 11] = [
    NpcEntry {
        sprite_id: 0x2C, x: 13, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 8, y: 16,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 30, trainer_set: 28,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 8, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 28, trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21, x: 18, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 21, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 28, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 30, trainer_set: 29,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 2, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xD1,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 4, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x24,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 21, y: 16,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x30,
    },
    NpcEntry {
        sprite_id: 0x42, x: 22, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x42, x: 25, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x42, x: 24, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCO6F: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x2C, x: 10, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C, x: 20, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B, x: 21, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B, x: 11, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C, x: 18, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 17, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 6,
        is_trainer: true,
        trainer_class: 30, trainer_set: 30,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 7, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: true,
        trainer_class: 28, trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 14, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 8,
        is_trainer: true,
        trainer_class: 30, trainer_set: 31,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 3, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x23,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 2, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x2E,
    },
];

pub static NPCS_SILPHCO7F: [NpcEntry; 11] = [
    NpcEntry {
        sprite_id: 0x2C, x: 1, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C, x: 13, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2C, x: 7, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x1B, x: 10, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 13, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 30, trainer_set: 32,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 2, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: true,
        trainer_class: 28, trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 20, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 7,
        is_trainer: true,
        trainer_class: 30, trainer_set: 33,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 19, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 8,
        is_trainer: true,
        trainer_class: 30, trainer_set: 34,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x02, x: 3, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 1, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x27,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 24, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xCB,
    },
];

pub static NPCS_SILPHCO8F: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x2C, x: 4, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 19, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 30, trainer_set: 35,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 10, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 28, trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 12, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 30, trainer_set: 36,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCO9F: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x29, x: 3, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 2, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 30, trainer_set: 37,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20, x: 21, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 28, trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18, x: 13, y: 16,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 30, trainer_set: 38,
        item_id: 0x00,
    },
];

pub static NPCS_SILPHCOELEVATOR: [NpcEntry; 0] = [];

pub static NPCS_TRADECENTER: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x01, x: 2, y: 2,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_UNDERGROUNDPATHNORTHSOUTH: [NpcEntry; 0] = [];

pub static NPCS_UNDERGROUNDPATHROUTE5: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x08, x: 2, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_UNDERGROUNDPATHROUTE6: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x0D, x: 2, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_UNDERGROUNDPATHROUTE7: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x0A, x: 2, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_UNDERGROUNDPATHROUTE7COPY: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x0D, x: 3, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0A, x: 2, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

