use crate::npc_data::{NpcEntry, NpcFacing, NpcMovement};

pub static NPCS_ROCKTUNNEL1F: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x0E,
        x: 7,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 5,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 17,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 23,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 37,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 17,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 22,
        y: 24,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 18,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 32,
        y: 24,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 19,
        item_id: 0x00,
    },
];

pub static NPCS_ROCKTUNNELB1F: [NpcEntry; 8] = [
    NpcEntry {
        sprite_id: 0x06,
        x: 11,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 6,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 3,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 20,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 30,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 14,
        y: 28,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 33,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 26,
        y: 30,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 5,
        item_id: 0x00,
    },
];

pub static NPCS_ROCKTUNNELPOKECENTER: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x29,
        x: 3,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10,
        x: 7,
        y: 3,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 2,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2A,
        x: 11,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROCKETHIDEOUTB1F: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x18,
        x: 26,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 12,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 18,
        y: 17,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 15,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 28,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 11,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x1D,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 9,
        y: 17,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x12,
    },
];

pub static NPCS_ROCKETHIDEOUTB2F: [NpcEntry; 5] = [
    NpcEntry {
        sprite_id: 0x18,
        x: 20,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 1,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x0A,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 16,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x31,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 6,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xCF,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 3,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x13,
    },
];

pub static NPCS_ROCKETHIDEOUTB3F: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x18,
        x: 10,
        y: 22,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 26,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 26,
        y: 17,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD2,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 20,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x28,
    },
];

pub static NPCS_ROCKETHIDEOUTB4F: [NpcEntry; 9] = [
    NpcEntry {
        sprite_id: 0x17,
        x: 25,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 29,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 23,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 16,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 26,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 17,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x18,
        x: 11,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 18,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 10,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x23,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 9,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xCA,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 12,
        y: 20,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x25,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 25,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x48,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 10,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x4A,
    },
];

pub static NPCS_ROCKETHIDEOUTELEVATOR: [NpcEntry; 0] = [];

pub static NPCS_ROUTE1: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x04,
        x: 5,
        y: 24,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 1,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 15,
        y: 13,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE10: [NpcEntry; 6] = [
    NpcEntry {
        sprite_id: 0x0C,
        x: 10,
        y: 44,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 3,
        y: 57,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 14,
        y: 64,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 7,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 7,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 3,
        y: 61,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 7,
        y: 54,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 8,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE11: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x0B,
        x: 10,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 26,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 13,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 36,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 12,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 22,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 45,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 33,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 43,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 45,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 12,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 22,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 12,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE11GATE1F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 4,
    y: 1,
    movement: NpcMovement(0),
    facing: NpcFacing(0),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE11GATE2F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x04,
        x: 4,
        y: 2,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x20,
        x: 2,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE12: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x43,
        x: 10,
        y: 62,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 14,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 5,
        y: 39,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 11,
        y: 92,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 14,
        y: 76,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 20,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 12,
        y: 40,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 9,
        y: 52,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 6,
        y: 87,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 14,
        y: 35,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xD8,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 5,
        y: 89,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x25,
    },
];

pub static NPCS_ROUTE12GATE1F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 1,
    y: 3,
    movement: NpcMovement(0),
    facing: NpcFacing(0),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE12GATE2F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x1D,
    x: 3,
    y: 4,
    movement: NpcMovement(1),
    facing: NpcFacing(0),
    range: 1,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE12SUPERRODHOUSE: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x27,
    x: 2,
    y: 4,
    movement: NpcMovement(0),
    facing: NpcFacing(3),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE13: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x07,
        x: 49,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 48,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 27,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 23,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 50,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 12,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 33,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 32,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 10,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 7,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 3,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE14: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x07,
        x: 4,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 15,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 12,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 16,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 14,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 17,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 15,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 6,
        y: 49,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 5,
        y: 39,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 4,
        y: 30,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 15,
        y: 30,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 4,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 2,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE15: [NpcEntry; 11] = [
    NpcEntry {
        sprite_id: 0x06,
        x: 41,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 20,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 53,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 21,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 31,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 35,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 53,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0F,
        x: 41,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 48,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 46,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 37,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 22,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 18,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 23,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 18,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 11,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xDC,
    },
];

pub static NPCS_ROUTE15GATE1F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 4,
    y: 1,
    movement: NpcMovement(0),
    facing: NpcFacing(0),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE15GATE2F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x20,
    x: 4,
    y: 2,
    movement: NpcMovement(0),
    facing: NpcFacing(0),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE16: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x12,
        x: 17,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 14,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 11,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 9,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 6,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 3,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x43,
        x: 26,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE16FLYHOUSE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x1D,
        x: 2,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09,
        x: 6,
        y: 4,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE16GATE1F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x31,
        x: 4,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 4,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE16GATE2F: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x35,
        x: 4,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x08,
        x: 2,
        y: 5,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE17: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x12,
        x: 12,
        y: 19,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 11,
        y: 16,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 4,
        y: 18,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 7,
        y: 32,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 14,
        y: 34,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 17,
        y: 58,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 2,
        y: 68,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 14,
        y: 98,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 5,
        y: 98,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x12,
        x: 10,
        y: 118,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 10,
        trainer_set: 12,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE18: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x07,
        x: 36,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 40,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 42,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 10,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE18GATE1F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 4,
    y: 1,
    movement: NpcMovement(0),
    facing: NpcFacing(0),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE18GATE2F: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x04,
    x: 4,
    y: 2,
    movement: NpcMovement(1),
    facing: NpcFacing(2),
    range: 2,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE19: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x07,
        x: 8,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 13,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 13,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 4,
        y: 27,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 16,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 9,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 8,
        y: 43,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 11,
        y: 43,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 9,
        y: 42,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 10,
        y: 44,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 14,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE2: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x3D,
        x: 13,
        y: 54,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x0A,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 13,
        y: 45,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x23,
    },
];

pub static NPCS_ROUTE20: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x22,
        x: 87,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 68,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 45,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 55,
        y: 14,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 24,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 38,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 87,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 34,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 23,
        trainer_set: 11,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 25,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 24,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 16,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 15,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 10,
        is_trainer: true,
        trainer_class: 18,
        trainer_set: 8,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE21: [NpcEntry; 9] = [
    NpcEntry {
        sprite_id: 0x2F,
        x: 4,
        y: 24,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 6,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 10,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 12,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 12,
        y: 30,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 16,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 16,
        y: 63,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 5,
        y: 71,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 15,
        y: 71,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 15,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 14,
        y: 56,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F,
        x: 17,
        y: 57,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 14,
        trainer_set: 10,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE22: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x02,
        x: 25,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x02,
        x: 25,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE22GATE: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 6,
    y: 2,
    movement: NpcMovement(0),
    facing: NpcFacing(2),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE23: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x31,
        x: 4,
        y: 35,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x31,
        x: 10,
        y: 56,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 8,
        y: 85,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x22,
        x: 11,
        y: 96,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 4,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x31,
        x: 12,
        y: 105,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x31,
        x: 8,
        y: 119,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x31,
        x: 8,
        y: 136,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 7,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE24: [NpcEntry; 8] = [
    NpcEntry {
        sprite_id: 0x07,
        x: 11,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 30,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 5,
        y: 20,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 11,
        y: 19,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 10,
        y: 22,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 11,
        y: 25,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 10,
        y: 28,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 11,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 10,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xF5,
    },
];

pub static NPCS_ROUTE25: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x04,
        x: 14,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 18,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 24,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 18,
        y: 8,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 32,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 37,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 8,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 23,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E,
        x: 13,
        y: 7,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 9,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 22,
        y: 2,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 10,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xDB,
    },
];

pub static NPCS_ROUTE2GATE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x20,
        x: 1,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 5,
        y: 4,
        movement: NpcMovement(1),
        facing: NpcFacing(2),
        range: 2,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE2TRADEHOUSE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x20,
        x: 2,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x37,
        x: 4,
        y: 1,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 2,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE3: [NpcEntry; 9] = [
    NpcEntry {
        sprite_id: 0x0C,
        x: 57,
        y: 11,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 10,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 14,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 16,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 19,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 23,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 22,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 1,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 24,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 33,
        y: 10,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 3,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE4: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x06,
        x: 9,
        y: 8,
        movement: NpcMovement(1),
        facing: NpcFacing(0),
        range: 0,
        text_id: 1,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 63,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D,
        x: 57,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 3,
        is_trainer: false,
        trainer_class: 0,
        trainer_set: 0,
        item_id: 0xCC,
    },
];

pub static NPCS_ROUTE5: [NpcEntry; 0] = [];

pub static NPCS_ROUTE5GATE: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 1,
    y: 3,
    movement: NpcMovement(0),
    facing: NpcFacing(3),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE6: [NpcEntry; 6] = [
    NpcEntry {
        sprite_id: 0x07,
        x: 10,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 11,
        y: 21,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 0,
        y: 15,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07,
        x: 11,
        y: 31,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 5,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 11,
        y: 30,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 6,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04,
        x: 19,
        y: 26,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 2,
        trainer_set: 11,
        item_id: 0x00,
    },
];

pub static NPCS_ROUTE6GATE: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 6,
    y: 2,
    movement: NpcMovement(0),
    facing: NpcFacing(2),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE7: [NpcEntry; 0] = [];

pub static NPCS_ROUTE7GATE: [NpcEntry; 1] = [NpcEntry {
    sprite_id: 0x31,
    x: 3,
    y: 1,
    movement: NpcMovement(0),
    facing: NpcFacing(0),
    range: 0,
    text_id: 1,
    is_trainer: false,
    trainer_class: 0,
    trainer_set: 0,
    item_id: 0x00,
}];

pub static NPCS_ROUTE8: [NpcEntry; 9] = [
    NpcEntry {
        sprite_id: 0x0C,
        x: 8,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 1,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 13,
        y: 9,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 2,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 42,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(1),
        range: 0,
        text_id: 3,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 26,
        y: 3,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 4,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 13,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C,
        x: 26,
        y: 4,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 5,
        is_trainer: true,
        trainer_class: 8,
        trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 26,
        y: 5,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 6,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 14,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 26,
        y: 6,
        movement: NpcMovement(0),
        facing: NpcFacing(3),
        range: 0,
        text_id: 7,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 15,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B,
        x: 46,
        y: 13,
        movement: NpcMovement(0),
        facing: NpcFacing(0),
        range: 0,
        text_id: 8,
        is_trainer: true,
        trainer_class: 17,
        trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06,
        x: 51,
        y: 12,
        movement: NpcMovement(0),
        facing: NpcFacing(2),
        range: 0,
        text_id: 9,
        is_trainer: true,
        trainer_class: 3,
        trainer_set: 16,
        item_id: 0x00,
    },
];
