use crate::npc_data::{NpcEntry, NpcMovement, NpcFacing};

pub static NPCS_UNDERGROUNDPATHROUTE8: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x0D, x: 3, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_UNDERGROUNDPATHWESTEAST: [NpcEntry; 0] = [];

pub static NPCS_VERMILIONCITY: [NpcEntry; 6] = [
    NpcEntry {
        sprite_id: 0x0F, x: 19, y: 7,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B, x: 14, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 19, y: 30,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B, x: 30, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x05, x: 29, y: 9,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 25, y: 27,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VERMILIONDOCK: [NpcEntry; 0] = [];

pub static NPCS_VERMILIONGYM: [NpcEntry; 5] = [
    NpcEntry {
        sprite_id: 0x21, x: 5, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 36, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 9, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 41, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C, x: 3, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 20, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 0, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 4, trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x24, x: 4, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VERMILIONMART: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x26, x: 0, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 5, y: 6,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 3, y: 3,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VERMILIONOLDRODHOUSE: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x27, x: 2, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VERMILIONPIDGEYHOUSE: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x04, x: 5, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09, x: 3, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x40, x: 4, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VERMILIONPOKECENTER: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x29, x: 3, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x27, x: 10, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x13, x: 5, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2A, x: 11, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VERMILIONTRADEHOUSE: [NpcEntry; 1] = [
    NpcEntry {
        sprite_id: 0x08, x: 3, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VICTORYROAD1F: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x06, x: 7, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 32, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 3, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 31, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 11, y: 0,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xF3,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 9, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 5, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 14, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 2, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VICTORYROAD2F: [NpcEntry; 13] = [
    NpcEntry {
        sprite_id: 0x0E, x: 12, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 24, trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C, x: 21, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 21, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 19, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 22, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C, x: 4, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 7, trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0C, x: 26, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 21, trainer_set: 5,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09, x: 11, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 27, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xD9,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 18, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x34,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 9, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xCD,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 11, y: 0,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x37,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 4, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 5, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 12,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 23, y: 16,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 13,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VICTORYROAD3F: [NpcEntry; 10] = [
    NpcEntry {
        sprite_id: 0x07, x: 28, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 31, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 7, y: 13,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 32, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 6, y: 14,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 31, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 13, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 32, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 26, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x36,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 7, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0xF7,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 22, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 13, y: 12,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 24, y: 10,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 22, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANCITY: [NpcEntry; 7] = [
    NpcEntry {
        sprite_id: 0x04, x: 13, y: 20,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B, x: 30, y: 8,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 30, y: 25,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0D, x: 17, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x48, x: 18, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2F, x: 6, y: 23,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0B, x: 17, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANFOREST: [NpcEntry; 8] = [
    NpcEntry {
        sprite_id: 0x04, x: 16, y: 43,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 30, y: 33,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 2, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 30, y: 19,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 2, trainer_set: 2,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 2, y: 18,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 2, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 25, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 5,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x0B,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 12, y: 29,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 6,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x14,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 1, y: 31,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x04,
    },
    NpcEntry {
        sprite_id: 0x04, x: 27, y: 40,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 8,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANFORESTNORTHGATE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x0C, x: 3, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x25, x: 2, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANFORESTSOUTHGATE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x0D, x: 8, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x08, x: 2, y: 4,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANGYM: [NpcEntry; 11] = [
    NpcEntry {
        sprite_id: 0x17, x: 2, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: true,
        trainer_class: 29, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 12, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: true,
        trainer_class: 31, trainer_set: 9,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E, x: 11, y: 11,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 3,
        is_trainer: true,
        trainer_class: 24, trainer_set: 6,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21, x: 10, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: true,
        trainer_class: 22, trainer_set: 3,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E, x: 3, y: 7,
        movement: NpcMovement(0), facing: NpcFacing(2),
        range: 0, text_id: 5,
        is_trainer: true,
        trainer_class: 24, trainer_set: 7,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 13, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 6,
        is_trainer: true,
        trainer_class: 31, trainer_set: 10,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x0E, x: 10, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 7,
        is_trainer: true,
        trainer_class: 24, trainer_set: 8,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x21, x: 2, y: 16,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 8,
        is_trainer: true,
        trainer_class: 22, trainer_set: 4,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 6, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 9,
        is_trainer: true,
        trainer_class: 31, trainer_set: 1,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x24, x: 16, y: 15,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 10,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 16, y: 9,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 11,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x35,
    },
];

pub static NPCS_VIRIDIANMART: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x26, x: 0, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(3),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x04, x: 5, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 3, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANNICKNAMEHOUSE: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x34, x: 5, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x08, x: 1, y: 4,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x09, x: 5, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(2),
        range: 2, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x42, x: 4, y: 0,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANPOKECENTER: [NpcEntry; 4] = [
    NpcEntry {
        sprite_id: 0x29, x: 3, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x10, x: 10, y: 5,
        movement: NpcMovement(1), facing: NpcFacing(0),
        range: 1, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x07, x: 4, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x2A, x: 11, y: 2,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 4,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_VIRIDIANSCHOOLHOUSE: [NpcEntry; 2] = [
    NpcEntry {
        sprite_id: 0x1D, x: 3, y: 5,
        movement: NpcMovement(0), facing: NpcFacing(1),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x06, x: 4, y: 1,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

pub static NPCS_WARDENSHOUSE: [NpcEntry; 3] = [
    NpcEntry {
        sprite_id: 0x2D, x: 2, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 1,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
    NpcEntry {
        sprite_id: 0x3D, x: 8, y: 3,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 2,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x28,
    },
    NpcEntry {
        sprite_id: 0x3F, x: 8, y: 4,
        movement: NpcMovement(0), facing: NpcFacing(0),
        range: 0, text_id: 3,
        is_trainer: false,
        trainer_class: 0, trainer_set: 0,
        item_id: 0x00,
    },
];

