use crate::moves::MoveId;
use crate::species::{GrowthRate, Species};
use crate::types::PokemonType;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaseStats {
    pub species: Species,
    pub hp: u8,
    pub attack: u8,
    pub defense: u8,
    pub speed: u8,
    pub special: u8,
    pub type1: PokemonType,
    pub type2: PokemonType,
    pub catch_rate: u8,
    pub base_exp: u8,
    pub initial_moves: [MoveId; 4],
    pub growth_rate: GrowthRate,
    pub tm_hm_flags: [u8; 7],
}

/// Get base stats for a species. Returns None for Species::None.
pub fn get_base_stats(species: Species) -> Option<&'static BaseStats> {
    let idx = species as usize;
    if idx == 0 || idx > 151 {
        None
    } else {
        Some(&BASE_STATS[idx - 1])
    }
}

pub const BASE_STATS: [BaseStats; 151] = [
    BaseStats {
        species: Species::Bulbasaur,
        hp: 45,
        attack: 49,
        defense: 49,
        speed: 45,
        special: 65,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 64,
        initial_moves: [MoveId::Tackle, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA4, 0x03, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Ivysaur,
        hp: 60,
        attack: 62,
        defense: 63,
        speed: 60,
        special: 80,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 141,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Growl,
            MoveId::LeechSeed,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA4, 0x03, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Venusaur,
        hp: 80,
        attack: 82,
        defense: 83,
        speed: 80,
        special: 100,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 208,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Growl,
            MoveId::LeechSeed,
            MoveId::VineWhip,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA4, 0x43, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Charmander,
        hp: 39,
        attack: 52,
        defense: 43,
        speed: 65,
        special: 50,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 45,
        base_exp: 65,
        initial_moves: [MoveId::Scratch, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB5, 0x03, 0x4F, 0xC8, 0xE3, 0x08, 0x26],
    },
    BaseStats {
        species: Species::Charmeleon,
        hp: 58,
        attack: 64,
        defense: 58,
        speed: 80,
        special: 65,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 45,
        base_exp: 142,
        initial_moves: [MoveId::Scratch, MoveId::Growl, MoveId::Ember, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB5, 0x03, 0x4F, 0xC8, 0xE3, 0x08, 0x26],
    },
    BaseStats {
        species: Species::Charizard,
        hp: 78,
        attack: 84,
        defense: 78,
        speed: 100,
        special: 85,
        type1: PokemonType::Fire,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 209,
        initial_moves: [MoveId::Scratch, MoveId::Growl, MoveId::Ember, MoveId::Leer],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB5, 0x43, 0x4F, 0xCE, 0xE3, 0x08, 0x26],
    },
    BaseStats {
        species: Species::Squirtle,
        hp: 44,
        attack: 48,
        defense: 65,
        speed: 43,
        special: 50,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 66,
        initial_moves: [MoveId::Tackle, MoveId::TailWhip, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x3F, 0x0F, 0xC8, 0x83, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Wartortle,
        hp: 59,
        attack: 63,
        defense: 80,
        speed: 58,
        special: 65,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 143,
        initial_moves: [
            MoveId::Tackle,
            MoveId::TailWhip,
            MoveId::Bubble,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x3F, 0x0F, 0xC8, 0x83, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Blastoise,
        hp: 79,
        attack: 83,
        defense: 100,
        speed: 78,
        special: 85,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 210,
        initial_moves: [
            MoveId::Tackle,
            MoveId::TailWhip,
            MoveId::Bubble,
            MoveId::WaterGun,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x7F, 0x0F, 0xCE, 0x83, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Caterpie,
        hp: 45,
        attack: 30,
        defense: 35,
        speed: 45,
        special: 20,
        type1: PokemonType::Bug,
        type2: PokemonType::Bug,
        catch_rate: 255,
        base_exp: 53,
        initial_moves: [
            MoveId::Tackle,
            MoveId::StringShot,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    },
    BaseStats {
        species: Species::Metapod,
        hp: 50,
        attack: 20,
        defense: 55,
        speed: 30,
        special: 25,
        type1: PokemonType::Bug,
        type2: PokemonType::Bug,
        catch_rate: 120,
        base_exp: 72,
        initial_moves: [MoveId::Harden, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    },
    BaseStats {
        species: Species::Butterfree,
        hp: 60,
        attack: 45,
        defense: 50,
        speed: 70,
        special: 80,
        type1: PokemonType::Bug,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 160,
        initial_moves: [MoveId::Confusion, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x2A, 0x43, 0x38, 0xF0, 0x43, 0x28, 0x02],
    },
    BaseStats {
        species: Species::Weedle,
        hp: 40,
        attack: 35,
        defense: 30,
        speed: 50,
        special: 20,
        type1: PokemonType::Bug,
        type2: PokemonType::Poison,
        catch_rate: 255,
        base_exp: 52,
        initial_moves: [
            MoveId::PoisonSting,
            MoveId::StringShot,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    },
    BaseStats {
        species: Species::Kakuna,
        hp: 45,
        attack: 25,
        defense: 50,
        speed: 35,
        special: 25,
        type1: PokemonType::Bug,
        type2: PokemonType::Poison,
        catch_rate: 120,
        base_exp: 71,
        initial_moves: [MoveId::Harden, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    },
    BaseStats {
        species: Species::Beedrill,
        hp: 65,
        attack: 80,
        defense: 40,
        speed: 75,
        special: 45,
        type1: PokemonType::Bug,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 159,
        initial_moves: [MoveId::FuryAttack, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x24, 0x43, 0x18, 0xC0, 0xC3, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Pidgey,
        hp: 40,
        attack: 45,
        defense: 40,
        speed: 56,
        special: 35,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 255,
        base_exp: 55,
        initial_moves: [MoveId::Gust, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x2A, 0x03, 0x08, 0xC0, 0x43, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Pidgeotto,
        hp: 63,
        attack: 60,
        defense: 55,
        speed: 71,
        special: 50,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 120,
        base_exp: 113,
        initial_moves: [MoveId::Gust, MoveId::SandAttack, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x2A, 0x03, 0x08, 0xC0, 0x43, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Pidgeot,
        hp: 83,
        attack: 80,
        defense: 75,
        speed: 91,
        special: 70,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 172,
        initial_moves: [
            MoveId::Gust,
            MoveId::SandAttack,
            MoveId::QuickAttack,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x2A, 0x43, 0x08, 0xC0, 0x43, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Rattata,
        hp: 30,
        attack: 56,
        defense: 35,
        speed: 72,
        special: 25,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 255,
        base_exp: 57,
        initial_moves: [MoveId::Tackle, MoveId::TailWhip, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x2F, 0x88, 0xC9, 0xC2, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Raticate,
        hp: 55,
        attack: 81,
        defense: 60,
        speed: 97,
        special: 50,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 90,
        base_exp: 116,
        initial_moves: [
            MoveId::Tackle,
            MoveId::TailWhip,
            MoveId::QuickAttack,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x7F, 0x88, 0xC9, 0xC2, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Spearow,
        hp: 40,
        attack: 60,
        defense: 30,
        speed: 70,
        special: 31,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 255,
        base_exp: 58,
        initial_moves: [MoveId::Peck, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x2A, 0x03, 0x08, 0xC0, 0x42, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Fearow,
        hp: 65,
        attack: 90,
        defense: 65,
        speed: 100,
        special: 61,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 90,
        base_exp: 162,
        initial_moves: [MoveId::Peck, MoveId::Growl, MoveId::Leer, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x2A, 0x43, 0x08, 0xC0, 0x42, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Ekans,
        hp: 35,
        attack: 60,
        defense: 44,
        speed: 55,
        special: 40,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 255,
        base_exp: 62,
        initial_moves: [MoveId::Wrap, MoveId::Leer, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x03, 0x18, 0xCE, 0x82, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Arbok,
        hp: 60,
        attack: 85,
        defense: 69,
        speed: 80,
        special: 65,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 90,
        base_exp: 147,
        initial_moves: [
            MoveId::Wrap,
            MoveId::Leer,
            MoveId::PoisonSting,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x43, 0x18, 0xCE, 0x82, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Pikachu,
        hp: 35,
        attack: 55,
        defense: 30,
        speed: 90,
        special: 50,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 190,
        base_exp: 82,
        initial_moves: [
            MoveId::Thundershock,
            MoveId::Growl,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x83, 0x8D, 0xC1, 0xC3, 0x18, 0x42],
    },
    BaseStats {
        species: Species::Raichu,
        hp: 60,
        attack: 90,
        defense: 55,
        speed: 100,
        special: 90,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 75,
        base_exp: 122,
        initial_moves: [
            MoveId::Thundershock,
            MoveId::Growl,
            MoveId::ThunderWave,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0xC3, 0x8D, 0xC1, 0xC3, 0x18, 0x42],
    },
    BaseStats {
        species: Species::Sandshrew,
        hp: 50,
        attack: 75,
        defense: 85,
        speed: 40,
        special: 30,
        type1: PokemonType::Ground,
        type2: PokemonType::Ground,
        catch_rate: 255,
        base_exp: 93,
        initial_moves: [MoveId::Scratch, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x03, 0x0D, 0xCE, 0xC2, 0x88, 0x26],
    },
    BaseStats {
        species: Species::Sandslash,
        hp: 75,
        attack: 100,
        defense: 110,
        speed: 65,
        special: 55,
        type1: PokemonType::Ground,
        type2: PokemonType::Ground,
        catch_rate: 90,
        base_exp: 163,
        initial_moves: [
            MoveId::Scratch,
            MoveId::SandAttack,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x43, 0x0D, 0xCE, 0xC2, 0x88, 0x26],
    },
    BaseStats {
        species: Species::NidoranF,
        hp: 55,
        attack: 47,
        defense: 52,
        speed: 41,
        special: 40,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 235,
        base_exp: 59,
        initial_moves: [MoveId::Growl, MoveId::Tackle, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA0, 0x23, 0x88, 0xC1, 0x83, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Nidorina,
        hp: 70,
        attack: 62,
        defense: 67,
        speed: 56,
        special: 55,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 120,
        base_exp: 117,
        initial_moves: [MoveId::Growl, MoveId::Tackle, MoveId::Scratch, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xE0, 0x3F, 0x88, 0xC1, 0x83, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Nidoqueen,
        hp: 90,
        attack: 82,
        defense: 87,
        speed: 76,
        special: 75,
        type1: PokemonType::Poison,
        type2: PokemonType::Ground,
        catch_rate: 45,
        base_exp: 194,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Scratch,
            MoveId::TailWhip,
            MoveId::BodySlam,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xF1, 0xFF, 0x8F, 0xC7, 0xA3, 0x88, 0x32],
    },
    BaseStats {
        species: Species::NidoranM,
        hp: 46,
        attack: 57,
        defense: 40,
        speed: 50,
        special: 40,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 235,
        base_exp: 60,
        initial_moves: [MoveId::Leer, MoveId::Tackle, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xE0, 0x23, 0x88, 0xC1, 0x83, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Nidorino,
        hp: 61,
        attack: 72,
        defense: 57,
        speed: 65,
        special: 55,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 120,
        base_exp: 118,
        initial_moves: [
            MoveId::Leer,
            MoveId::Tackle,
            MoveId::HornAttack,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xE0, 0x3F, 0x88, 0xC1, 0x83, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Nidoking,
        hp: 81,
        attack: 92,
        defense: 77,
        speed: 85,
        special: 75,
        type1: PokemonType::Poison,
        type2: PokemonType::Ground,
        catch_rate: 45,
        base_exp: 195,
        initial_moves: [
            MoveId::Tackle,
            MoveId::HornAttack,
            MoveId::PoisonSting,
            MoveId::Thrash,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xF1, 0xFF, 0x8F, 0xC7, 0xA3, 0x88, 0x32],
    },
    BaseStats {
        species: Species::Clefairy,
        hp: 70,
        attack: 45,
        defense: 48,
        speed: 35,
        special: 60,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 150,
        base_exp: 68,
        initial_moves: [MoveId::Pound, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Fast,
        tm_hm_flags: [0xB1, 0x3F, 0xAF, 0xF1, 0xA7, 0x38, 0x63],
    },
    BaseStats {
        species: Species::Clefable,
        hp: 95,
        attack: 70,
        defense: 73,
        speed: 60,
        special: 85,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 25,
        base_exp: 129,
        initial_moves: [
            MoveId::Sing,
            MoveId::Doubleslap,
            MoveId::Minimize,
            MoveId::Metronome,
        ],
        growth_rate: GrowthRate::Fast,
        tm_hm_flags: [0xB1, 0x7F, 0xAF, 0xF1, 0xA7, 0x38, 0x63],
    },
    BaseStats {
        species: Species::Vulpix,
        hp: 38,
        attack: 41,
        defense: 40,
        speed: 65,
        special: 65,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 190,
        base_exp: 63,
        initial_moves: [MoveId::Ember, MoveId::TailWhip, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x03, 0x08, 0xC8, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Ninetales,
        hp: 73,
        attack: 76,
        defense: 75,
        speed: 100,
        special: 100,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 75,
        base_exp: 178,
        initial_moves: [
            MoveId::Ember,
            MoveId::TailWhip,
            MoveId::QuickAttack,
            MoveId::Roar,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x43, 0x08, 0xC8, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Jigglypuff,
        hp: 115,
        attack: 45,
        defense: 20,
        speed: 20,
        special: 25,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 170,
        base_exp: 76,
        initial_moves: [MoveId::Sing, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Fast,
        tm_hm_flags: [0xB1, 0x3F, 0xAF, 0xF1, 0xA3, 0x38, 0x63],
    },
    BaseStats {
        species: Species::Wigglytuff,
        hp: 140,
        attack: 70,
        defense: 45,
        speed: 45,
        special: 50,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 50,
        base_exp: 109,
        initial_moves: [
            MoveId::Sing,
            MoveId::Disable,
            MoveId::DefenseCurl,
            MoveId::Doubleslap,
        ],
        growth_rate: GrowthRate::Fast,
        tm_hm_flags: [0xB1, 0x7F, 0xAF, 0xF1, 0xA3, 0x38, 0x63],
    },
    BaseStats {
        species: Species::Zubat,
        hp: 40,
        attack: 45,
        defense: 35,
        speed: 55,
        special: 40,
        type1: PokemonType::Poison,
        type2: PokemonType::Flying,
        catch_rate: 255,
        base_exp: 54,
        initial_moves: [MoveId::LeechLife, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x2A, 0x03, 0x18, 0xC0, 0x42, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Golbat,
        hp: 75,
        attack: 80,
        defense: 70,
        speed: 90,
        special: 75,
        type1: PokemonType::Poison,
        type2: PokemonType::Flying,
        catch_rate: 90,
        base_exp: 171,
        initial_moves: [
            MoveId::LeechLife,
            MoveId::Screech,
            MoveId::Bite,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x2A, 0x43, 0x18, 0xC0, 0x42, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Oddish,
        hp: 45,
        attack: 50,
        defense: 55,
        speed: 30,
        special: 75,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 255,
        base_exp: 78,
        initial_moves: [MoveId::Absorb, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x24, 0x03, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Gloom,
        hp: 60,
        attack: 65,
        defense: 70,
        speed: 40,
        special: 85,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 120,
        base_exp: 132,
        initial_moves: [
            MoveId::Absorb,
            MoveId::Poisonpowder,
            MoveId::StunSpore,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x24, 0x03, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Vileplume,
        hp: 75,
        attack: 80,
        defense: 85,
        speed: 50,
        special: 100,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 184,
        initial_moves: [
            MoveId::StunSpore,
            MoveId::SleepPowder,
            MoveId::Acid,
            MoveId::PetalDance,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA4, 0x43, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Paras,
        hp: 35,
        attack: 70,
        defense: 55,
        speed: 25,
        special: 55,
        type1: PokemonType::Bug,
        type2: PokemonType::Grass,
        catch_rate: 190,
        base_exp: 70,
        initial_moves: [MoveId::Scratch, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x03, 0x38, 0xC8, 0x83, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Parasect,
        hp: 60,
        attack: 95,
        defense: 80,
        speed: 30,
        special: 80,
        type1: PokemonType::Bug,
        type2: PokemonType::Grass,
        catch_rate: 75,
        base_exp: 128,
        initial_moves: [
            MoveId::Scratch,
            MoveId::StunSpore,
            MoveId::LeechLife,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x43, 0x38, 0xC8, 0x83, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Venonat,
        hp: 60,
        attack: 55,
        defense: 50,
        speed: 45,
        special: 40,
        type1: PokemonType::Bug,
        type2: PokemonType::Poison,
        catch_rate: 190,
        base_exp: 75,
        initial_moves: [MoveId::Tackle, MoveId::Disable, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x03, 0x38, 0xD0, 0x03, 0x28, 0x02],
    },
    BaseStats {
        species: Species::Venomoth,
        hp: 70,
        attack: 65,
        defense: 60,
        speed: 90,
        special: 90,
        type1: PokemonType::Bug,
        type2: PokemonType::Poison,
        catch_rate: 75,
        base_exp: 138,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Disable,
            MoveId::Poisonpowder,
            MoveId::LeechLife,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x2A, 0x43, 0x38, 0xF0, 0x43, 0x28, 0x02],
    },
    BaseStats {
        species: Species::Diglett,
        hp: 10,
        attack: 55,
        defense: 25,
        speed: 95,
        special: 45,
        type1: PokemonType::Ground,
        type2: PokemonType::Ground,
        catch_rate: 255,
        base_exp: 81,
        initial_moves: [MoveId::Scratch, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x03, 0x08, 0xCE, 0x02, 0x88, 0x02],
    },
    BaseStats {
        species: Species::Dugtrio,
        hp: 35,
        attack: 80,
        defense: 50,
        speed: 120,
        special: 70,
        type1: PokemonType::Ground,
        type2: PokemonType::Ground,
        catch_rate: 50,
        base_exp: 153,
        initial_moves: [MoveId::Scratch, MoveId::Growl, MoveId::Dig, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x43, 0x08, 0xCE, 0x02, 0x88, 0x02],
    },
    BaseStats {
        species: Species::Meowth,
        hp: 40,
        attack: 45,
        defense: 35,
        speed: 90,
        special: 40,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 255,
        base_exp: 69,
        initial_moves: [MoveId::Scratch, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x8F, 0x88, 0xC1, 0xC2, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Persian,
        hp: 65,
        attack: 70,
        defense: 60,
        speed: 115,
        special: 65,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 90,
        base_exp: 148,
        initial_moves: [
            MoveId::Scratch,
            MoveId::Growl,
            MoveId::Bite,
            MoveId::Screech,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0xCF, 0x88, 0xC1, 0xC2, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Psyduck,
        hp: 50,
        attack: 52,
        defense: 48,
        speed: 55,
        special: 50,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 190,
        base_exp: 80,
        initial_moves: [MoveId::Scratch, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0xBF, 0x0F, 0xC8, 0xC2, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Golduck,
        hp: 80,
        attack: 82,
        defense: 78,
        speed: 85,
        special: 80,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 75,
        base_exp: 174,
        initial_moves: [
            MoveId::Scratch,
            MoveId::TailWhip,
            MoveId::Disable,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0xFF, 0x0F, 0xC8, 0xC2, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Mankey,
        hp: 40,
        attack: 80,
        defense: 35,
        speed: 70,
        special: 35,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 190,
        base_exp: 74,
        initial_moves: [MoveId::Scratch, MoveId::Leer, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x83, 0x8F, 0xC9, 0xC6, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Primeape,
        hp: 65,
        attack: 105,
        defense: 60,
        speed: 95,
        special: 60,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 75,
        base_exp: 149,
        initial_moves: [
            MoveId::Scratch,
            MoveId::Leer,
            MoveId::KarateChop,
            MoveId::FurySwipes,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0xC3, 0x8F, 0xC9, 0xC6, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Growlithe,
        hp: 55,
        attack: 70,
        defense: 45,
        speed: 60,
        special: 50,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 190,
        base_exp: 91,
        initial_moves: [MoveId::Bite, MoveId::Roar, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xA0, 0x03, 0x48, 0xC8, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Arcanine,
        hp: 90,
        attack: 110,
        defense: 80,
        speed: 95,
        special: 80,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 75,
        base_exp: 213,
        initial_moves: [MoveId::Roar, MoveId::Ember, MoveId::Leer, MoveId::TakeDown],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xA0, 0x43, 0x48, 0xE8, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Poliwag,
        hp: 40,
        attack: 50,
        defense: 40,
        speed: 90,
        special: 40,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 255,
        base_exp: 77,
        initial_moves: [MoveId::Bubble, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA0, 0x3F, 0x08, 0xD0, 0x82, 0x28, 0x12],
    },
    BaseStats {
        species: Species::Poliwhirl,
        hp: 65,
        attack: 65,
        defense: 65,
        speed: 90,
        special: 50,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 120,
        base_exp: 131,
        initial_moves: [
            MoveId::Bubble,
            MoveId::Hypnosis,
            MoveId::WaterGun,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x3F, 0x0F, 0xD6, 0x86, 0x28, 0x32],
    },
    BaseStats {
        species: Species::Poliwrath,
        hp: 90,
        attack: 85,
        defense: 95,
        speed: 70,
        special: 70,
        type1: PokemonType::Water,
        type2: PokemonType::Fighting,
        catch_rate: 45,
        base_exp: 185,
        initial_moves: [
            MoveId::Hypnosis,
            MoveId::WaterGun,
            MoveId::Doubleslap,
            MoveId::BodySlam,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x7F, 0x0F, 0xD6, 0x86, 0x28, 0x32],
    },
    BaseStats {
        species: Species::Abra,
        hp: 25,
        attack: 20,
        defense: 15,
        speed: 90,
        special: 105,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 200,
        base_exp: 73,
        initial_moves: [MoveId::Teleport, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xF0, 0x87, 0x38, 0x43],
    },
    BaseStats {
        species: Species::Kadabra,
        hp: 40,
        attack: 35,
        defense: 30,
        speed: 105,
        special: 120,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 100,
        base_exp: 145,
        initial_moves: [
            MoveId::Teleport,
            MoveId::Confusion,
            MoveId::Disable,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xF8, 0x87, 0x38, 0x43],
    },
    BaseStats {
        species: Species::Alakazam,
        hp: 55,
        attack: 50,
        defense: 45,
        speed: 120,
        special: 135,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 50,
        base_exp: 186,
        initial_moves: [
            MoveId::Teleport,
            MoveId::Confusion,
            MoveId::Disable,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x43, 0x0F, 0xF8, 0x87, 0x38, 0x43],
    },
    BaseStats {
        species: Species::Machop,
        hp: 70,
        attack: 80,
        defense: 50,
        speed: 35,
        special: 35,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 180,
        base_exp: 88,
        initial_moves: [MoveId::KarateChop, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xCE, 0xA6, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Machoke,
        hp: 80,
        attack: 100,
        defense: 70,
        speed: 45,
        special: 50,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 90,
        base_exp: 146,
        initial_moves: [
            MoveId::KarateChop,
            MoveId::LowKick,
            MoveId::Leer,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xCE, 0xA6, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Machamp,
        hp: 90,
        attack: 130,
        defense: 80,
        speed: 55,
        special: 65,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 45,
        base_exp: 193,
        initial_moves: [
            MoveId::KarateChop,
            MoveId::LowKick,
            MoveId::Leer,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x43, 0x0F, 0xCE, 0xA6, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Bellsprout,
        hp: 50,
        attack: 75,
        defense: 35,
        speed: 40,
        special: 70,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 255,
        base_exp: 84,
        initial_moves: [MoveId::VineWhip, MoveId::Growth, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x24, 0x03, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Weepinbell,
        hp: 65,
        attack: 90,
        defense: 50,
        speed: 55,
        special: 85,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 120,
        base_exp: 151,
        initial_moves: [MoveId::VineWhip, MoveId::Growth, MoveId::Wrap, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x24, 0x03, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Victreebel,
        hp: 80,
        attack: 105,
        defense: 65,
        speed: 70,
        special: 100,
        type1: PokemonType::Grass,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 191,
        initial_moves: [
            MoveId::SleepPowder,
            MoveId::StunSpore,
            MoveId::Acid,
            MoveId::RazorLeaf,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA4, 0x43, 0x38, 0xC0, 0x03, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Tentacool,
        hp: 40,
        attack: 40,
        defense: 35,
        speed: 70,
        special: 100,
        type1: PokemonType::Water,
        type2: PokemonType::Poison,
        catch_rate: 190,
        base_exp: 105,
        initial_moves: [MoveId::Acid, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x24, 0x3F, 0x18, 0xC0, 0x83, 0x08, 0x16],
    },
    BaseStats {
        species: Species::Tentacruel,
        hp: 80,
        attack: 70,
        defense: 65,
        speed: 100,
        special: 120,
        type1: PokemonType::Water,
        type2: PokemonType::Poison,
        catch_rate: 60,
        base_exp: 205,
        initial_moves: [MoveId::Acid, MoveId::Supersonic, MoveId::Wrap, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x24, 0x7F, 0x18, 0xC0, 0x83, 0x08, 0x16],
    },
    BaseStats {
        species: Species::Geodude,
        hp: 40,
        attack: 80,
        defense: 100,
        speed: 20,
        special: 30,
        type1: PokemonType::Rock,
        type2: PokemonType::Ground,
        catch_rate: 255,
        base_exp: 86,
        initial_moves: [MoveId::Tackle, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA1, 0x03, 0x0F, 0xCE, 0x2E, 0xC8, 0x22],
    },
    BaseStats {
        species: Species::Graveler,
        hp: 55,
        attack: 95,
        defense: 115,
        speed: 35,
        special: 45,
        type1: PokemonType::Rock,
        type2: PokemonType::Ground,
        catch_rate: 120,
        base_exp: 134,
        initial_moves: [
            MoveId::Tackle,
            MoveId::DefenseCurl,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xA1, 0x03, 0x0F, 0xCE, 0x2E, 0xC8, 0x22],
    },
    BaseStats {
        species: Species::Golem,
        hp: 80,
        attack: 110,
        defense: 130,
        speed: 45,
        special: 55,
        type1: PokemonType::Rock,
        type2: PokemonType::Ground,
        catch_rate: 45,
        base_exp: 177,
        initial_moves: [
            MoveId::Tackle,
            MoveId::DefenseCurl,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x43, 0x0F, 0xCE, 0x2E, 0xC8, 0x22],
    },
    BaseStats {
        species: Species::Ponyta,
        hp: 50,
        attack: 85,
        defense: 55,
        speed: 90,
        special: 65,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 190,
        base_exp: 152,
        initial_moves: [MoveId::Ember, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xE0, 0x03, 0x08, 0xC0, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Rapidash,
        hp: 65,
        attack: 100,
        defense: 70,
        speed: 105,
        special: 80,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 60,
        base_exp: 192,
        initial_moves: [
            MoveId::Ember,
            MoveId::TailWhip,
            MoveId::Stomp,
            MoveId::Growl,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xE0, 0x43, 0x08, 0xC0, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Slowpoke,
        hp: 90,
        attack: 65,
        defense: 65,
        speed: 15,
        special: 40,
        type1: PokemonType::Water,
        type2: PokemonType::Psychic,
        catch_rate: 190,
        base_exp: 99,
        initial_moves: [MoveId::Confusion, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0xBF, 0x08, 0xFE, 0xE3, 0x38, 0x73],
    },
    BaseStats {
        species: Species::Slowbro,
        hp: 95,
        attack: 75,
        defense: 110,
        speed: 30,
        special: 80,
        type1: PokemonType::Water,
        type2: PokemonType::Psychic,
        catch_rate: 75,
        base_exp: 164,
        initial_moves: [
            MoveId::Confusion,
            MoveId::Disable,
            MoveId::Headbutt,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0xFF, 0x0F, 0xFE, 0xE3, 0x38, 0x73],
    },
    BaseStats {
        species: Species::Magnemite,
        hp: 25,
        attack: 35,
        defense: 70,
        speed: 45,
        special: 95,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 190,
        base_exp: 89,
        initial_moves: [MoveId::Tackle, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x03, 0x88, 0xE1, 0x43, 0x18, 0x42],
    },
    BaseStats {
        species: Species::Magneton,
        hp: 50,
        attack: 60,
        defense: 95,
        speed: 70,
        special: 120,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 60,
        base_exp: 161,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Sonicboom,
            MoveId::Thundershock,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x43, 0x88, 0xE1, 0x43, 0x18, 0x42],
    },
    BaseStats {
        species: Species::Farfetchd,
        hp: 52,
        attack: 65,
        defense: 55,
        speed: 60,
        special: 58,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 94,
        initial_moves: [MoveId::Peck, MoveId::SandAttack, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xAE, 0x03, 0x08, 0xC0, 0xC3, 0x08, 0x0E],
    },
    BaseStats {
        species: Species::Doduo,
        hp: 35,
        attack: 85,
        defense: 45,
        speed: 75,
        special: 35,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 190,
        base_exp: 96,
        initial_moves: [MoveId::Peck, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA8, 0x03, 0x08, 0xC0, 0x83, 0x0C, 0x0B],
    },
    BaseStats {
        species: Species::Dodrio,
        hp: 60,
        attack: 110,
        defense: 70,
        speed: 100,
        special: 60,
        type1: PokemonType::Normal,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 158,
        initial_moves: [
            MoveId::Peck,
            MoveId::Growl,
            MoveId::FuryAttack,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA8, 0x43, 0x08, 0xC0, 0x83, 0x0C, 0x0B],
    },
    BaseStats {
        species: Species::Seel,
        hp: 65,
        attack: 45,
        defense: 55,
        speed: 45,
        special: 70,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 190,
        base_exp: 100,
        initial_moves: [MoveId::Headbutt, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xE0, 0xBF, 0x08, 0xC0, 0x82, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Dewgong,
        hp: 90,
        attack: 70,
        defense: 80,
        speed: 70,
        special: 95,
        type1: PokemonType::Water,
        type2: PokemonType::Ice,
        catch_rate: 75,
        base_exp: 176,
        initial_moves: [
            MoveId::Headbutt,
            MoveId::Growl,
            MoveId::AuroraBeam,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xE0, 0xFF, 0x08, 0xC0, 0x82, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Grimer,
        hp: 80,
        attack: 80,
        defense: 50,
        speed: 25,
        special: 40,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 190,
        base_exp: 90,
        initial_moves: [MoveId::Pound, MoveId::Disable, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x00, 0x98, 0xC1, 0x2A, 0x48, 0x02],
    },
    BaseStats {
        species: Species::Muk,
        hp: 105,
        attack: 105,
        defense: 75,
        speed: 50,
        special: 65,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 75,
        base_exp: 157,
        initial_moves: [
            MoveId::Pound,
            MoveId::Disable,
            MoveId::PoisonGas,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x40, 0x98, 0xC1, 0x2A, 0x48, 0x02],
    },
    BaseStats {
        species: Species::Shellder,
        hp: 30,
        attack: 65,
        defense: 100,
        speed: 40,
        special: 45,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 190,
        base_exp: 97,
        initial_moves: [MoveId::Tackle, MoveId::Withdraw, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x20, 0x3F, 0x08, 0xE0, 0x4B, 0x48, 0x13],
    },
    BaseStats {
        species: Species::Cloyster,
        hp: 50,
        attack: 95,
        defense: 180,
        speed: 70,
        special: 85,
        type1: PokemonType::Water,
        type2: PokemonType::Ice,
        catch_rate: 60,
        base_exp: 203,
        initial_moves: [
            MoveId::Withdraw,
            MoveId::Supersonic,
            MoveId::Clamp,
            MoveId::AuroraBeam,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x20, 0x7F, 0x08, 0xE0, 0x4B, 0x48, 0x13],
    },
    BaseStats {
        species: Species::Gastly,
        hp: 30,
        attack: 35,
        defense: 30,
        speed: 80,
        special: 100,
        type1: PokemonType::Ghost,
        type2: PokemonType::Poison,
        catch_rate: 190,
        base_exp: 95,
        initial_moves: [
            MoveId::Lick,
            MoveId::ConfuseRay,
            MoveId::NightShade,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x20, 0x00, 0x98, 0xD1, 0x0A, 0x6A, 0x02],
    },
    BaseStats {
        species: Species::Haunter,
        hp: 45,
        attack: 50,
        defense: 45,
        speed: 95,
        special: 115,
        type1: PokemonType::Ghost,
        type2: PokemonType::Poison,
        catch_rate: 90,
        base_exp: 126,
        initial_moves: [
            MoveId::Lick,
            MoveId::ConfuseRay,
            MoveId::NightShade,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0x20, 0x00, 0x98, 0xD1, 0x0A, 0x6A, 0x02],
    },
    BaseStats {
        species: Species::Gengar,
        hp: 60,
        attack: 65,
        defense: 60,
        speed: 110,
        special: 130,
        type1: PokemonType::Ghost,
        type2: PokemonType::Poison,
        catch_rate: 45,
        base_exp: 190,
        initial_moves: [
            MoveId::Lick,
            MoveId::ConfuseRay,
            MoveId::NightShade,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xB1, 0x43, 0x9F, 0xD1, 0x8E, 0x6A, 0x22],
    },
    BaseStats {
        species: Species::Onix,
        hp: 35,
        attack: 45,
        defense: 160,
        speed: 70,
        special: 30,
        type1: PokemonType::Rock,
        type2: PokemonType::Ground,
        catch_rate: 45,
        base_exp: 108,
        initial_moves: [MoveId::Tackle, MoveId::Screech, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x03, 0x08, 0xCE, 0x8A, 0xC8, 0x22],
    },
    BaseStats {
        species: Species::Drowzee,
        hp: 60,
        attack: 48,
        defense: 45,
        speed: 42,
        special: 90,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 190,
        base_exp: 102,
        initial_moves: [MoveId::Pound, MoveId::Hypnosis, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xF0, 0x87, 0x3A, 0x43],
    },
    BaseStats {
        species: Species::Hypno,
        hp: 85,
        attack: 73,
        defense: 70,
        speed: 67,
        special: 115,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 75,
        base_exp: 165,
        initial_moves: [
            MoveId::Pound,
            MoveId::Hypnosis,
            MoveId::Disable,
            MoveId::Confusion,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x43, 0x0F, 0xF0, 0x87, 0x3A, 0x43],
    },
    BaseStats {
        species: Species::Krabby,
        hp: 30,
        attack: 105,
        defense: 90,
        speed: 50,
        special: 25,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 225,
        base_exp: 115,
        initial_moves: [MoveId::Bubble, MoveId::Leer, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x3F, 0x08, 0xC0, 0x02, 0x08, 0x36],
    },
    BaseStats {
        species: Species::Kingler,
        hp: 55,
        attack: 130,
        defense: 115,
        speed: 75,
        special: 50,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 60,
        base_exp: 206,
        initial_moves: [MoveId::Bubble, MoveId::Leer, MoveId::Vicegrip, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x7F, 0x08, 0xC0, 0x02, 0x08, 0x36],
    },
    BaseStats {
        species: Species::Voltorb,
        hp: 40,
        attack: 30,
        defense: 50,
        speed: 100,
        special: 55,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 190,
        base_exp: 103,
        initial_moves: [MoveId::Tackle, MoveId::Screech, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x01, 0x88, 0xE1, 0x4B, 0x58, 0x42],
    },
    BaseStats {
        species: Species::Electrode,
        hp: 60,
        attack: 50,
        defense: 70,
        speed: 140,
        special: 80,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 60,
        base_exp: 150,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Screech,
            MoveId::Sonicboom,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x41, 0x88, 0xE1, 0xCB, 0x58, 0x42],
    },
    BaseStats {
        species: Species::Exeggcute,
        hp: 60,
        attack: 40,
        defense: 80,
        speed: 40,
        special: 60,
        type1: PokemonType::Grass,
        type2: PokemonType::Psychic,
        catch_rate: 90,
        base_exp: 98,
        initial_moves: [
            MoveId::Barrage,
            MoveId::Hypnosis,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x20, 0x03, 0x08, 0xF0, 0x1B, 0x68, 0x02],
    },
    BaseStats {
        species: Species::Exeggutor,
        hp: 95,
        attack: 95,
        defense: 85,
        speed: 55,
        special: 125,
        type1: PokemonType::Grass,
        type2: PokemonType::Psychic,
        catch_rate: 45,
        base_exp: 212,
        initial_moves: [
            MoveId::Barrage,
            MoveId::Hypnosis,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x20, 0x43, 0x38, 0xF0, 0x1B, 0x68, 0x22],
    },
    BaseStats {
        species: Species::Cubone,
        hp: 50,
        attack: 50,
        defense: 95,
        speed: 35,
        special: 40,
        type1: PokemonType::Ground,
        type2: PokemonType::Ground,
        catch_rate: 190,
        base_exp: 87,
        initial_moves: [MoveId::BoneClub, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x3F, 0x0F, 0xCE, 0xA2, 0x08, 0x22],
    },
    BaseStats {
        species: Species::Marowak,
        hp: 60,
        attack: 80,
        defense: 110,
        speed: 45,
        special: 50,
        type1: PokemonType::Ground,
        type2: PokemonType::Ground,
        catch_rate: 75,
        base_exp: 124,
        initial_moves: [
            MoveId::BoneClub,
            MoveId::Growl,
            MoveId::Leer,
            MoveId::FocusEnergy,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x7F, 0x0F, 0xCE, 0xA2, 0x08, 0x22],
    },
    BaseStats {
        species: Species::Hitmonlee,
        hp: 50,
        attack: 120,
        defense: 53,
        speed: 87,
        special: 35,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 45,
        base_exp: 139,
        initial_moves: [
            MoveId::DoubleKick,
            MoveId::Meditate,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xC0, 0xC6, 0x08, 0x22],
    },
    BaseStats {
        species: Species::Hitmonchan,
        hp: 50,
        attack: 105,
        defense: 79,
        speed: 76,
        special: 35,
        type1: PokemonType::Fighting,
        type2: PokemonType::Fighting,
        catch_rate: 45,
        base_exp: 140,
        initial_moves: [
            MoveId::CometPunch,
            MoveId::Agility,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x03, 0x0F, 0xC0, 0xC6, 0x08, 0x22],
    },
    BaseStats {
        species: Species::Lickitung,
        hp: 90,
        attack: 55,
        defense: 75,
        speed: 30,
        special: 60,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 45,
        base_exp: 127,
        initial_moves: [MoveId::Wrap, MoveId::Supersonic, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB5, 0x7F, 0x8F, 0xC7, 0xA2, 0x08, 0x36],
    },
    BaseStats {
        species: Species::Koffing,
        hp: 40,
        attack: 65,
        defense: 95,
        speed: 35,
        special: 60,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 190,
        base_exp: 114,
        initial_moves: [MoveId::Tackle, MoveId::Smog, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x00, 0x88, 0xC1, 0x2A, 0x48, 0x02],
    },
    BaseStats {
        species: Species::Weezing,
        hp: 65,
        attack: 90,
        defense: 120,
        speed: 60,
        special: 85,
        type1: PokemonType::Poison,
        type2: PokemonType::Poison,
        catch_rate: 60,
        base_exp: 173,
        initial_moves: [MoveId::Tackle, MoveId::Smog, MoveId::Sludge, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x40, 0x88, 0xC1, 0x2A, 0x48, 0x02],
    },
    BaseStats {
        species: Species::Rhyhorn,
        hp: 80,
        attack: 85,
        defense: 95,
        speed: 25,
        special: 30,
        type1: PokemonType::Ground,
        type2: PokemonType::Rock,
        catch_rate: 120,
        base_exp: 135,
        initial_moves: [MoveId::HornAttack, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xE0, 0x03, 0x88, 0xCF, 0xA2, 0x88, 0x22],
    },
    BaseStats {
        species: Species::Rhydon,
        hp: 105,
        attack: 130,
        defense: 120,
        speed: 40,
        special: 45,
        type1: PokemonType::Ground,
        type2: PokemonType::Rock,
        catch_rate: 60,
        base_exp: 204,
        initial_moves: [
            MoveId::HornAttack,
            MoveId::Stomp,
            MoveId::TailWhip,
            MoveId::FuryAttack,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xF1, 0xFF, 0x8F, 0xCF, 0xA2, 0x88, 0x32],
    },
    BaseStats {
        species: Species::Chansey,
        hp: 250,
        attack: 5,
        defense: 5,
        speed: 50,
        special: 105,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 30,
        base_exp: 255,
        initial_moves: [
            MoveId::Pound,
            MoveId::Doubleslap,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Fast,
        tm_hm_flags: [0xB1, 0x7F, 0xAF, 0xF1, 0xB7, 0x39, 0x63],
    },
    BaseStats {
        species: Species::Tangela,
        hp: 65,
        attack: 55,
        defense: 115,
        speed: 60,
        special: 100,
        type1: PokemonType::Grass,
        type2: PokemonType::Grass,
        catch_rate: 45,
        base_exp: 166,
        initial_moves: [MoveId::Constrict, MoveId::Bind, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA4, 0x43, 0x38, 0xC0, 0x82, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Kangaskhan,
        hp: 105,
        attack: 95,
        defense: 80,
        speed: 90,
        special: 40,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 45,
        base_exp: 175,
        initial_moves: [MoveId::CometPunch, MoveId::Rage, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x7F, 0x8F, 0xC7, 0xA2, 0x88, 0x32],
    },
    BaseStats {
        species: Species::Horsea,
        hp: 30,
        attack: 40,
        defense: 70,
        speed: 60,
        special: 70,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 225,
        base_exp: 83,
        initial_moves: [MoveId::Bubble, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x3F, 0x08, 0xC0, 0xC2, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Seadra,
        hp: 55,
        attack: 65,
        defense: 95,
        speed: 85,
        special: 95,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 75,
        base_exp: 155,
        initial_moves: [
            MoveId::Bubble,
            MoveId::Smokescreen,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x7F, 0x08, 0xC0, 0xC2, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Goldeen,
        hp: 45,
        attack: 67,
        defense: 60,
        speed: 63,
        special: 50,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 225,
        base_exp: 111,
        initial_moves: [MoveId::Peck, MoveId::TailWhip, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x60, 0x3F, 0x08, 0xC0, 0xC2, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Seaking,
        hp: 80,
        attack: 92,
        defense: 65,
        speed: 68,
        special: 80,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 60,
        base_exp: 170,
        initial_moves: [
            MoveId::Peck,
            MoveId::TailWhip,
            MoveId::Supersonic,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x60, 0x7F, 0x08, 0xC0, 0xC2, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Staryu,
        hp: 30,
        attack: 45,
        defense: 55,
        speed: 85,
        special: 70,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 225,
        base_exp: 106,
        initial_moves: [MoveId::Tackle, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x20, 0x3F, 0x88, 0xF1, 0xC3, 0x38, 0x53],
    },
    BaseStats {
        species: Species::Starmie,
        hp: 60,
        attack: 75,
        defense: 85,
        speed: 115,
        special: 100,
        type1: PokemonType::Water,
        type2: PokemonType::Psychic,
        catch_rate: 60,
        base_exp: 207,
        initial_moves: [
            MoveId::Tackle,
            MoveId::WaterGun,
            MoveId::Harden,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x20, 0x7F, 0x88, 0xF1, 0xC3, 0x38, 0x53],
    },
    BaseStats {
        species: Species::MrMime,
        hp: 40,
        attack: 45,
        defense: 65,
        speed: 90,
        special: 100,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 45,
        base_exp: 136,
        initial_moves: [
            MoveId::Confusion,
            MoveId::Barrier,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x43, 0xAF, 0xF1, 0x87, 0x38, 0x42],
    },
    BaseStats {
        species: Species::Scyther,
        hp: 70,
        attack: 110,
        defense: 80,
        speed: 105,
        special: 55,
        type1: PokemonType::Bug,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 187,
        initial_moves: [
            MoveId::QuickAttack,
            MoveId::None,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x24, 0x43, 0x08, 0xC0, 0xC2, 0x08, 0x06],
    },
    BaseStats {
        species: Species::Jynx,
        hp: 65,
        attack: 50,
        defense: 35,
        speed: 95,
        special: 95,
        type1: PokemonType::Ice,
        type2: PokemonType::Psychic,
        catch_rate: 45,
        base_exp: 137,
        initial_moves: [
            MoveId::Pound,
            MoveId::LovelyKiss,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x7F, 0x0F, 0xF0, 0x87, 0x28, 0x02],
    },
    BaseStats {
        species: Species::Electabuzz,
        hp: 65,
        attack: 83,
        defense: 57,
        speed: 105,
        special: 85,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 45,
        base_exp: 156,
        initial_moves: [
            MoveId::QuickAttack,
            MoveId::Leer,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x43, 0x8F, 0xF1, 0xC7, 0x38, 0x62],
    },
    BaseStats {
        species: Species::Magmar,
        hp: 65,
        attack: 95,
        defense: 57,
        speed: 93,
        special: 85,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 45,
        base_exp: 167,
        initial_moves: [MoveId::Ember, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB1, 0x43, 0x0F, 0xF0, 0xA6, 0x28, 0x22],
    },
    BaseStats {
        species: Species::Pinsir,
        hp: 65,
        attack: 125,
        defense: 100,
        speed: 85,
        special: 55,
        type1: PokemonType::Bug,
        type2: PokemonType::Bug,
        catch_rate: 45,
        base_exp: 200,
        initial_moves: [MoveId::Vicegrip, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xA4, 0x43, 0x0D, 0xC0, 0x02, 0x08, 0x26],
    },
    BaseStats {
        species: Species::Tauros,
        hp: 75,
        attack: 100,
        defense: 95,
        speed: 110,
        special: 70,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 45,
        base_exp: 211,
        initial_moves: [MoveId::Tackle, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xE0, 0x73, 0x88, 0xC7, 0xA2, 0x08, 0x22],
    },
    BaseStats {
        species: Species::Magikarp,
        hp: 20,
        attack: 10,
        defense: 55,
        speed: 80,
        special: 20,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 255,
        base_exp: 20,
        initial_moves: [MoveId::Splash, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    },
    BaseStats {
        species: Species::Gyarados,
        hp: 95,
        attack: 125,
        defense: 79,
        speed: 81,
        special: 100,
        type1: PokemonType::Water,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 214,
        initial_moves: [
            MoveId::Bite,
            MoveId::DragonRage,
            MoveId::Leer,
            MoveId::HydroPump,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xA0, 0x7F, 0xC8, 0xC1, 0xA3, 0x08, 0x32],
    },
    BaseStats {
        species: Species::Lapras,
        hp: 130,
        attack: 85,
        defense: 80,
        speed: 60,
        special: 95,
        type1: PokemonType::Water,
        type2: PokemonType::Ice,
        catch_rate: 45,
        base_exp: 219,
        initial_moves: [MoveId::WaterGun, MoveId::Growl, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xE0, 0x7F, 0xE8, 0xD1, 0x83, 0x28, 0x32],
    },
    BaseStats {
        species: Species::Ditto,
        hp: 48,
        attack: 48,
        defense: 48,
        speed: 48,
        special: 48,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 35,
        base_exp: 61,
        initial_moves: [MoveId::Transform, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
    },
    BaseStats {
        species: Species::Eevee,
        hp: 55,
        attack: 55,
        defense: 50,
        speed: 55,
        special: 65,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 45,
        base_exp: 92,
        initial_moves: [
            MoveId::Tackle,
            MoveId::SandAttack,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x03, 0x08, 0xC0, 0xC3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Vaporeon,
        hp: 130,
        attack: 65,
        defense: 60,
        speed: 65,
        special: 110,
        type1: PokemonType::Water,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 196,
        initial_moves: [
            MoveId::Tackle,
            MoveId::SandAttack,
            MoveId::QuickAttack,
            MoveId::WaterGun,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x7F, 0x08, 0xC0, 0xC3, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Jolteon,
        hp: 65,
        attack: 65,
        defense: 60,
        speed: 130,
        special: 110,
        type1: PokemonType::Electric,
        type2: PokemonType::Electric,
        catch_rate: 45,
        base_exp: 197,
        initial_moves: [
            MoveId::Tackle,
            MoveId::SandAttack,
            MoveId::QuickAttack,
            MoveId::Thundershock,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x43, 0x88, 0xC1, 0xC3, 0x18, 0x42],
    },
    BaseStats {
        species: Species::Flareon,
        hp: 65,
        attack: 130,
        defense: 60,
        speed: 65,
        special: 110,
        type1: PokemonType::Fire,
        type2: PokemonType::Fire,
        catch_rate: 45,
        base_exp: 198,
        initial_moves: [
            MoveId::Tackle,
            MoveId::SandAttack,
            MoveId::QuickAttack,
            MoveId::Ember,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x43, 0x08, 0xC0, 0xE3, 0x08, 0x02],
    },
    BaseStats {
        species: Species::Porygon,
        hp: 65,
        attack: 60,
        defense: 70,
        speed: 40,
        special: 75,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 45,
        base_exp: 130,
        initial_moves: [
            MoveId::Tackle,
            MoveId::Sharpen,
            MoveId::Conversion,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0x20, 0x73, 0x88, 0xF1, 0xC3, 0x38, 0x43],
    },
    BaseStats {
        species: Species::Omanyte,
        hp: 35,
        attack: 40,
        defense: 100,
        speed: 35,
        special: 90,
        type1: PokemonType::Rock,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 120,
        initial_moves: [
            MoveId::WaterGun,
            MoveId::Withdraw,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x3F, 0x08, 0xC0, 0x03, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Omastar,
        hp: 70,
        attack: 60,
        defense: 125,
        speed: 55,
        special: 115,
        type1: PokemonType::Rock,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 199,
        initial_moves: [
            MoveId::WaterGun,
            MoveId::Withdraw,
            MoveId::HornAttack,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xE0, 0x7F, 0x0D, 0xC0, 0x83, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Kabuto,
        hp: 30,
        attack: 80,
        defense: 90,
        speed: 55,
        special: 45,
        type1: PokemonType::Rock,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 119,
        initial_moves: [MoveId::Scratch, MoveId::Harden, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xA0, 0x3F, 0x08, 0xC0, 0x03, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Kabutops,
        hp: 60,
        attack: 115,
        defense: 105,
        speed: 80,
        special: 70,
        type1: PokemonType::Rock,
        type2: PokemonType::Water,
        catch_rate: 45,
        base_exp: 201,
        initial_moves: [
            MoveId::Scratch,
            MoveId::Harden,
            MoveId::Absorb,
            MoveId::None,
        ],
        growth_rate: GrowthRate::MediumFast,
        tm_hm_flags: [0xB6, 0x7F, 0x0D, 0xC0, 0x83, 0x08, 0x12],
    },
    BaseStats {
        species: Species::Aerodactyl,
        hp: 80,
        attack: 105,
        defense: 65,
        speed: 130,
        special: 60,
        type1: PokemonType::Rock,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 202,
        initial_moves: [
            MoveId::WingAttack,
            MoveId::Agility,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x2A, 0x43, 0x48, 0xC0, 0x63, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Snorlax,
        hp: 160,
        attack: 110,
        defense: 65,
        speed: 30,
        special: 65,
        type1: PokemonType::Normal,
        type2: PokemonType::Normal,
        catch_rate: 25,
        base_exp: 154,
        initial_moves: [
            MoveId::Headbutt,
            MoveId::Amnesia,
            MoveId::Rest,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xB1, 0xFF, 0xAF, 0xD7, 0xAF, 0xA8, 0x32],
    },
    BaseStats {
        species: Species::Articuno,
        hp: 90,
        attack: 85,
        defense: 100,
        speed: 85,
        special: 125,
        type1: PokemonType::Ice,
        type2: PokemonType::Flying,
        catch_rate: 3,
        base_exp: 215,
        initial_moves: [MoveId::Peck, MoveId::IceBeam, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x2A, 0x7F, 0x08, 0xC0, 0x43, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Zapdos,
        hp: 90,
        attack: 90,
        defense: 85,
        speed: 100,
        special: 125,
        type1: PokemonType::Electric,
        type2: PokemonType::Flying,
        catch_rate: 3,
        base_exp: 216,
        initial_moves: [
            MoveId::Thundershock,
            MoveId::DrillPeck,
            MoveId::None,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x2A, 0x43, 0x88, 0xC1, 0x43, 0x1C, 0x4A],
    },
    BaseStats {
        species: Species::Moltres,
        hp: 90,
        attack: 100,
        defense: 90,
        speed: 90,
        special: 125,
        type1: PokemonType::Fire,
        type2: PokemonType::Flying,
        catch_rate: 3,
        base_exp: 217,
        initial_moves: [MoveId::Peck, MoveId::FireSpin, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0x2A, 0x43, 0x08, 0xC0, 0x63, 0x0C, 0x0A],
    },
    BaseStats {
        species: Species::Dratini,
        hp: 41,
        attack: 64,
        defense: 45,
        speed: 50,
        special: 50,
        type1: PokemonType::Dragon,
        type2: PokemonType::Dragon,
        catch_rate: 45,
        base_exp: 67,
        initial_moves: [MoveId::Wrap, MoveId::Leer, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xA0, 0x3F, 0xC8, 0xC1, 0xE3, 0x18, 0x12],
    },
    BaseStats {
        species: Species::Dragonair,
        hp: 61,
        attack: 84,
        defense: 65,
        speed: 70,
        special: 70,
        type1: PokemonType::Dragon,
        type2: PokemonType::Dragon,
        catch_rate: 45,
        base_exp: 144,
        initial_moves: [
            MoveId::Wrap,
            MoveId::Leer,
            MoveId::ThunderWave,
            MoveId::None,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xE0, 0x3F, 0xC8, 0xC1, 0xE3, 0x18, 0x12],
    },
    BaseStats {
        species: Species::Dragonite,
        hp: 91,
        attack: 134,
        defense: 95,
        speed: 80,
        special: 100,
        type1: PokemonType::Dragon,
        type2: PokemonType::Flying,
        catch_rate: 45,
        base_exp: 218,
        initial_moves: [
            MoveId::Wrap,
            MoveId::Leer,
            MoveId::ThunderWave,
            MoveId::Agility,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xE2, 0x7F, 0xC8, 0xC1, 0xE3, 0x18, 0x32],
    },
    BaseStats {
        species: Species::Mewtwo,
        hp: 106,
        attack: 110,
        defense: 90,
        speed: 130,
        special: 154,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 3,
        base_exp: 220,
        initial_moves: [
            MoveId::Confusion,
            MoveId::Disable,
            MoveId::Swift,
            MoveId::PsychicM,
        ],
        growth_rate: GrowthRate::Slow,
        tm_hm_flags: [0xB1, 0xFF, 0xAF, 0xF1, 0xAF, 0x38, 0x63],
    },
    BaseStats {
        species: Species::Mew,
        hp: 100,
        attack: 100,
        defense: 100,
        speed: 100,
        special: 100,
        type1: PokemonType::Psychic,
        type2: PokemonType::Psychic,
        catch_rate: 45,
        base_exp: 64,
        initial_moves: [MoveId::Pound, MoveId::None, MoveId::None, MoveId::None],
        growth_rate: GrowthRate::MediumSlow,
        tm_hm_flags: [0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F],
    },
];
